# -*- coding: utf-8 -*-
# 브랜드 한글명 → 영어명 매핑

BRAND_MAPPING = {
    # A-Z, 0-9
    '032씨': '032c', '1011갤러리': '1011 Gallery', '119레오': '119REO', '1989스탠다드': '1989 Standard', '1993스튜디오': '1993 Studio',
    '2000아카이브스': '2000Archives', '201 브리드': '201 BREATHE', '2113 스튜디오': '2113 Studio', '222(이투둘)': '222', '24/7 시리즈': '24/7 Series',
    '24/7 시리즈 포 우먼': '24/7 Series for Women', '2호': '2HO', '320쇼룸': '320 Showroom', '33아파트먼트': '33 Apartment', '38컴온커먼': '38 COMEONCOMMON',
    '39이티씨': '39etc', '69슬램': '69slam', '999휴머니티': '999Humanity', 'MM6': 'MM6 Maison Margiela', '[공식몰]카카오프렌즈': 'Kakao Friends',
    'HIS 헤지스': 'HIS HAZZYS',

    # ㄱ
    '가까이 유니언즈': 'gaggai unions', '가든익스프레스': 'GARDEN EXPRESS', '가먼트레이블': 'GARMENT LABLE', '가연리': 'GAYEONRI', '가치.': 'Gachi.',
    '가터갤러리': 'Garter Gallery', '감마갤러리': 'Gamma Gallery', '갓샵': 'GOD POUND', '강정석': 'KANG JUNG SEOK', '객': 'GAEK', '게리루더': 'GERRY ROOKER',
    '게스': 'Guess', '게스언더웨어': 'Guess Underwear', '게인스보로': 'Gainsboro', '겐조': 'Kenzo', '경': 'KYUNG', '고고르르': 'gogolele', '고낙': 'GONAK', '고목': 'GOMOK',
    '고어웨어': 'GOREWEAR', '고요웨어': 'goyowear', '고코리': 'GOCORI', '곤니치와봉쥬르': 'Konnichiwa Bonjour', '골드퍼센트': 'GOLD PERCENT',
    '골든구스': 'Golden Goose', '골든선샤인': 'GOLDEN SUNSHINE', '골라': 'Gola', '골스튜디오': 'Goalstudio', '공백': 'gongbaek', '공에이프런': 'GONG APRON',
    '구공페스트': '90fest', '구보': 'KUBO', '구스아일랜드': 'Goose Island', '구테': 'GUTE', '국립현대미술관 온라인숍 미술가게': 'MMCA',
    '굿니스': 'GOODNESS', '굿덴': 'GOODDEN', '굿라이프 어드벤처클럽 (글락)': 'GLACK', '굿라이프웍스': 'Goodlifeworks', '굿온': 'Good On',
    '굿하비클럽': 'GOOD HOBBY CLUB', '귤메달': 'GYUL MEDAL', '그라미치': 'Gramicci', '그라운드웨이브': 'GROUNDWAVE', '그라인': 'GRHINE',
    '그란투리스모': 'GRAN TURISMO', '그랑크루': 'GRAND CRU', '그레이데시온': 'GRAYDECION', '그레이버': 'Graver', '그레이블러밧': 'GREY BLURVATT',
    '그레일즈': 'Grailz', '그로브': 'Grove', '그리니치': 'GREENWICH', '그리미': 'GRIMEY', '그린블리스': 'greenbliss', '그립스와니': 'GRIP SWANY',
    '근니': 'GEUNNI', '글랙': 'GLACK', '글러브웍스': 'GLOVEWORKS', '글로니': 'GLOWNY', '글로우': 'GLOW', '기명': 'KIMMYUNG', '기준': 'KIJUN',
    '기준 맨': 'KIJUN MEN', '길단': 'GILDAN', '까르네 볼렌떼': 'Carne Bollente', '까웨': 'K-WAY', '꼬떼': 'coté', '꼬모니노즈': 'COMONINOZ',
    '꼼파뇨': 'Compagno', '꾸아페': 'ccuaffe',

    # ㄴ
    '나누슈카': 'Nanushka', '나무사이로': 'Namusairo', '나비버스': 'NAVIVERSE', '나아나나': 'NAANANA', '나우': 'nau', '나우앤투모로우': 'NOWANDTOMORROW',
    '나이스고스트클럽': 'NICE GHOST CLUB', '나이스웨더': 'NICE WEATHER', '나이스클랍': 'NICE CLAUP', '나이젤 카본': 'Nigel Cabourn',
    '나인어코드': 'NINE ACCORD', '나체': 'NACHE', '날씨': 'NALSSI', '낫띵리튼': 'Nothing Written', '낫띵이즈베럴댄미': 'NOTHING IS BETTER THAN ME',
    '낫아워스': 'NOT OURS', '낫온리포투데이': 'NOTONLYFORTODAY', '낫포너드': 'NOT FOR NERD', '내셔널지오그래픽': 'National Geographic',
    '너버스': 'NERVOUS', '너티새비지': 'NUTTY SAVAGE', '넌블랭크': 'NONBLANK', '널': 'NULL', '네더월드': 'NETHERWORLD',
    '네버트라이네버노': 'NEVERTRYNEVERKNOW', '네스티킥': 'NASTY KICK', '네이더스': 'NEITHERS', '네이머클로딩': 'NAMER CLOTHING',
    '네이비': 'NAVY', '네이키드서프클럽': 'NAKED SURF CLUB', '네파': 'NEPA', '넥스트도어립스': 'NEXTDOORLIPS', '노드 스튜디오': 'NODE STUDIO',
    '노드 아카이브': 'NODE ARCHIVE', '노드랩스': 'NODELABS', '노르딕아일랜드': 'NORDIC ISLAND', '노르디스크': 'Nordisk', '노리타케': 'Noritake',
    '노매뉴얼': 'Nomanual', '노머': 'NOMER', '노스페이스': 'The North Face', '노앙': 'NOHANT', '노우트': 'NOUT', '노운': 'KNOUN',
    '노운베러': 'KNOWN BETTER', '노이스': 'NOICE', '노이어': 'NOIRER', '노이어 포 우먼': 'NOIRER FOR WOMEN', '노이즈': 'NOIZZ',
    '노이커먼': 'NOYCOMMON', '노컨텐츠': 'NOCONTENDS', '노쿨러스': 'NOCULUS', '노클': 'NOKL', '노클루': 'NO CLUE', '노티카': 'NAUTICA',
    '논타입': 'NONTYPE', '논플로어': 'NONFLOOR', '놉녹': 'NOPKNOP', '누마레 포 맨': 'NUMARE FOR MEN', '누벨바그 코리아': 'NOUVELLE VAGUE KOREA',
    '누보텐': 'NOUVEAUTEIN', '누아누': 'NOUANOU', '누아클레 맨': 'NOIRCLAIR MEN', '누이비': 'NUIBE', '누클래식': 'NUCLASSIC',
    '누팍': 'NUPARCC', '뉴믹스커피': 'NEWMICS COFFEE', '뉴발란스': 'New Balance', '뉴비': 'NEWB', '뉴에라': 'New Era', '뉴오브': 'NEWAVE',
    '뉴욕웍스': 'NEWYORKWORKS', '뉴해빗': 'NEW HABIT', '니더 에이': 'NIEDER A', '니즈': 'KNEEZ', '니티드': 'knitted', '니히': 'NIHII', '널':'NUL',
    '닉앤니콜': 'NICK&NICOLE', '닐튼': 'NILTON',

    # ㄷ
    '다로': 'DARO', '다미쉬': 'DAMISH', '다이닛': 'Dinit', '다이나핏': 'DYNAFIT', '다이아몬드 레이라': 'DIAMOND LAYLA', '다이와 스펙라이프': 'DAIWA SPECLIFE',
    '다이클레즈': 'DICLEZ', '다임': 'Dime', '다코다스튜디오': 'DAKOTA STUDIO', '단델': 'DANDEL', '댄크디어': 'DANKDIR', '댕글드랍': 'DANGLEDROP',
    '더 긱스': 'THE GEEKS', '더 드리머': 'THE DREAMER', '더 라이': 'THE RYE', '더 레스큐': 'THE RESQ', '더 멜로우 가드너': 'THE MELLOW GARDENER',
    '더 새터데이 이브닝 포스트': 'THE SATURDAY EVENING POST', '더 스캇렉': 'THE SCOTT REK', '더 스톨른 가먼트': 'THE STOLEN GARMENT',
    '더 스튜디오 케이': 'THE STUDIO K', '더가스펠오브': 'THE GOSPEL OF', '더그레이티스트': 'THE GREATEST', '더니트컴퍼니': 'THE KNIT COMPANY',
    '더룸': 'THE LOOM', '더무지': 'THE MUJI', '더뮤지엄비지터': 'THE MUSEUM VISITOR', '더밀루이': 'THE MILRUI', '더바넷': 'THE BARNET',
    '더바이닐하우스': 'THE VINYL HOUSE', '더발론': 'THE BALLON', '더블유브이프로젝트': 'WV PROJECT', '더블유엠': 'WM', '더블유엠씨': 'WMC',
    '더블유워크샵': 'W WORKSHOP', '더샤인 캐시미어': 'THE SHINE CASHMERE', '더셔츠스튜디오': 'THE SHIRTS STUDIO', '더솔루션즈': 'THE SOLUTIONS',
    '더스웻': 'THE SWEAT', '더스테': 'THE STE', '더스토리': 'THE STORI', '더에이본': 'THE AVON', '더엘로': 'THE ELO',
    '더오리지널클로딩클럽': 'THE ORIGINAL CLOTHING CLUB', '더오유': 'THEOHYOU', '더왈드': 'THE WALD', '더웨더이즈어썸': 'THE WEATHER IS AWESOME',
    '더잽스': 'THE ZAPS', '더콜디스트모먼트': 'THE COLDEST MOMENT', '더패브릭': 'THE FABRIC', '더페니': 'THE PENNI', '덕다이브': 'DUCKDIVE',
    '던스트': 'Dunst', '데님인디고마스터': 'DENIM INDIGO MASTER', '데밀': 'DEMIL', '데상트': 'Descente', '데어드': 'DARED',
    '데우스 엑스 마키나': 'DEUS EX MACHINA', '데이브앤데이즈': 'DAVE & DAZE', '데이즈데이즈': 'DAZE DAYZ', '데이지 신드롬': 'DAISY SYNDROME',
    '데일리인': 'DAILY INN', '데카브': 'DECAVE', '데케트': 'DECKET', '데프가먼츠': 'DEAF GARMENTS', '덴메이드': 'DENMADE', '덴스': 'THENCE',
    '델디오': 'DELDEO', '델리센트': 'DELICENT', '뎁크': 'DEPK', '뎃츠잇': 'THATSIT', '도미넌트': 'DOMINANT', '도시서점': 'DOSI BOOKS', '도우터': 'DAUGHTER',
    '도큐먼트': 'DOCUMENT', '도프제이슨': 'DOFFJASON', '돈애스크마이플랜': "DON'T ASK MY PLAN", '듀엘': 'DEWL', '듀테로': 'DEUTERO', '듑벨': 'DUPBEL',
    '드니벨': 'DENIVEL', '드니벨 맨즈': 'DENIVEL MENZ', '드로우핏': 'DRAW FIT', '드롤드무슈': 'Drôle de Monsieur', '드리프트아웃': 'DRIFTOUT', '드릭스': 'DREEX',
    '드베르망': 'DEVERMAN', '드퐁': 'DEPOND', '디그': 'DIG', '디그낙12': 'D.GNAK12', '디그랜드마틴': 'D.GRAND MARTIN', '디그레': 'DEGRE',
    '디더블유에스이': 'DWSE', '디미트리블랙': 'DIMITRI BLACK', '디비젼': 'DIVISION', '디셈버텐': 'DECEMBER 10', '디스이즈네버댓': 'thisisneverthat',
    '디스커버리 익스페디션': 'Discovery Expedition', '디스커스 애슬레틱': 'DISCUS ATHLETIC', '디스코드사운드': 'DISCHORD SOUND',
    '디스트나인': 'DIST NINE', '디스트릭트 비전': 'DISTRICT VISION', '디써티원': 'D31', '디아도라': 'diadora', '디안티플랫폼': 'D-ANTIDOTE',
    '디애니': 'THE ANNIE', '디애퍼처': 'THE APERTURE', '디앤에스알': 'DNSR', '디야니': 'DIYANI', '디어스토커': 'DEERSTALKER', '디오디': 'DOD',
    '디콤파스': 'DCOMPASS', '디클립': 'DCLIP', '디키즈': 'Dickies', '디파인': 'DEFINE', '디프리크': 'D-PRIQUE', '땡땡샵': 'DDANG DDANG SHOP',
    '떼뚜': 'TETU', '떼마': 'THEMA', '뚜누': 'TEOUNOU', '뚜오미오': 'TUOMIO', '띰': 'THIM', '띵크': 'THINC', '띵크플랜트': 'THINKPLANT',

    # ㄹ
    '라드인사이드': 'RADINSIDE', '라디네오': 'RADINEO', '라라폭스': 'LALAFOX', '라멀 마메종': "L'AMEL MAMAISON", '라메레이': 'LAMEREI',
    '라모랭': 'LAMOLIN', '라벨 아카이브': 'LABEL ARCHIVE', '라비드': 'RAVID', '라이즈앤빌로우': 'RISE AND BELOW', '라임라이크': 'LIMELIKE',
    '라츠': 'LOTS', '라코스모': 'LACOSMO', '라코스테': 'LACOSTE', '라티젠': 'LATIZEN', '라파예트': 'LAFAYETTE', '라퍼': 'LAPPER',
    '락케이크': 'ROCKCAKE', '락피쉬웨더웨어': 'Rockfish Weatherwear', '란라': 'RANRA', '랄': 'RAL', '랑가주망': "L'ENGAGEMENT",
    '래스': 'RATH', '래코드': 'RE;CODE', '랜덤노이즈': 'RANDOM NOISE', '랩': 'LAB', '랩12': 'LAB12', '랩원오원': 'LAB101',
    '랭글러': 'Wrangler', '랭앤루': 'LANG&LU', '러기드하우스': 'RUGGED HOUSE', '러닝하이': 'RUNNING HIGH', '러벤티나': 'LEVENTINA',
    '러브어스유': 'LOVEUSYOU', '러브엠': 'LOVEM', '러브이즈트루': 'LUV IS TRUE', '러브포티': 'LOVE40', '러쉬': 'LUSH',
    '러스틱클럽': 'RUSTIC CLUB', '러프': 'ROUGH', '러프사이드': 'ROUGHSIDE', '러프사이드 화이트라벨': 'ROUGHSIDE WHITE LABEL',
    '럭키슈에뜨': 'LUCKY CHOUETTE', '런던그로서리마켓': 'LONDON GROCERY MARKET', '레더리': 'LEATHERY', '레드락': 'REDROCK',
    '레드윙': 'Red Wing', '레미': 'REMI', '레스트앤레크레이션': 'Rest & Recreation', '레시타': 'RECITA', '레씨토': 'LECITO',
    '레이디 화이트': 'Lady White Co.', '레이디볼륨': 'LADY VOLUME', '레이버러스': 'LABORIOUS', '레이브': 'RAIVE', '레이브 맨': 'RAIVE MEN',
    '레이블리스': 'LABELLESS', '레이지지': 'RAGEAZY', '레이트 체크아웃': 'LATE CHECKOUT', '레인스': 'RAINS', '레터': 'LETTER',
    '레테라': 'LETTERA', '레테르코모': 'LETERCOMO', '레투': 'LEDEUX', '레페르': 'LEPÈRE', '레프트서울': 'LEFT SEOUL',
    '로드 존 그레이': 'LORD JOHN GREY', '로라로라': 'rolarola', '로렌 랄프 로렌': 'Lauren Ralph Lauren', '로리엣': 'RORIET',
    '로맨시크': 'ROMANCHIC', '로맨틱크라운': 'Romantic Crown', '로서울': 'ROH SEOUL', '로센스': 'ROSENCE', '로스코': 'ROTHCO',
    '로시로우': 'ROSYROW', '로씨로씨': 'rocci rocci', '로아': 'ROA', '로아드로아': 'ROADROAR', '로얄시티파크': 'ROYAL CITY PARK',
    '로얄위': 'ROYALWE', '로어즈': 'ROARS', '로에스': 'ROES', '로에일': 'ROEIL', '로열 클럽 홀리데이': 'ROYAL CLUB HOLIDAY',
    '로우': 'RHO', '로우클래식': 'LOW CLASSIC', '로우투로우': 'ROW TO ROW', '로이터로이터': 'REUTER REUTER', '로제프란츠': 'ROSEFRANTZ',
    '로컬스온리': 'LOCALS ONLY', '로코베이직': 'LOCO BASIC', '로파이': 'LOFI', '로프티 오퍼스': 'LOFTY OPUS', '록히드마틴': 'LOCKHEED MARTIN',
    '론론': 'RONRON', '론즈데일': 'LONSDALE', '롤링스튜디오': 'ROLLING STUDIO', '루루서울': 'LULUSEOUL', '루스프로덕트': 'LOOSE PRODUCT',
    '루에브르': 'LOEUVRE', '루이브': 'LUIB', '루트파인더': 'ROOTFINDER', '루프트맨션': 'LUFT MANSION', '룩캐스트': 'LOOKAST',
    '률앤와이': 'RYUL AND Y', '르917': 'LE917', '르917 옴므': 'LE917 HOMME', '르꼬끄스포르티브': 'le coq sportif', '르네제이': 'RENEJ',
    '르닐': 'LENIL', '르라레': 'LE RARE', '르마드': 'LEMARD', '르모호': 'LEMOHO', '르몽생미셸': 'LE MONT ST MICHEL', '르미너': 'LEMINOR',
    '르바': 'LEVAR', '르베이스먼트': 'LE BASEMENT', '르보클래식': 'LEBEAUCLASSIC', '르비에르': 'LEVIERE', '르샵블랑': 'LESHOP BLANC',
    '르수기아뜰리에': 'LESUGI ATELIER', '르쏠레일마띠네': 'LE SOLEIL MATINEE', '르씨': 'LECCI', '르아르': 'LE ARE', '르아브': 'LE HAVRE',
    '르아워': 'LE HOUR', '르에떼': 'LE ETE', '르엠토': 'LEMT', '르티그레': 'LE TIGRE', '르퍼스널오더': 'LE PERSONAL ORDER',
    '르하스': 'LEHAS', '리': 'Lee', '리 키즈': 'LEE KIDS', '리;카인드': 'RE;KIND', '리가즈': 'REGAZ', '리군스튜디오': 'RIGUN STUDIO',
    '리넥츠': 'RENECTS', '리디피': 'LDP', '리모네': 'LIMONE', '리바이스': "Levi's", '리버레이더스': 'LIBERAIDORS', '리버스': 'REBIRTH',
    '리복': 'Reebok', '리볼드': 'REBOLD', '리블렛츠더블엠': 'LIBLETS W.M', '리빙톤 르아 레비스 123': 'LIVINGSTONE LUA LEVIS 123',
    '리셉션': 'RECEPTION', '리슈': 'LYSHU', '리스펙트': 'RESPECT', '리시트': 'RECEIPT', '리에떼': 'LIETE', '리엔드코': 'RE_NDCO',
    '리올그': 'REORG', '리우 옴므': 'RIEU HOMME', '리유니': 'REUNI', '리이': 'RIYI', '리지': 'LIZZY', '리틀템포 디자인': 'LITTLE TEMPO DESIGN',
    '리플레이컨테이너': 'REPLAY CONTAINER', '릴리헤이즈': 'LILYHAZE',

    # ㅁ
    '마가렛호웰': 'Margaret Howell', '마더그라운드': 'mother ground', '마뗑킴': 'Matin Kim', '마로이': 'MAROI', '마롭': 'MAROP', '마롯': 'MAROT', '마르제': 'MARGE',
    '마르지하우스': 'MARGE HOUSE', '마른파이브': 'MAREUN5', '마리끌레르': 'marie claire', '마리떼 키즈': 'MARITHE KIDS',
    '마리떼 프랑소와 저버': 'Marithe Francois Girbaud', '마린세르': 'MARINE SERRE', '마무트': 'MAMMUT', '마스랜더': 'MARS LANDER',
    '마스마룰즈': 'MASMARULEZ', '마스테프': 'MASTEFF', '마욜': 'MAYOL', '마우이앤선즈': 'MAUI AND SONS', '마이네임이즈피터': 'MY NAME IS PETER',
    '마이딥블루메모리즈': 'MY DEEP BLUE MEMORIES', '마이리틀스타': 'MY LITTLE STAR', '마이쉘': 'MY SHELL', '마이아': 'MAIA',
    '마이콥': 'MYKOP', '마인데님': 'MINEDENIM', '마인드브릿지': 'Mind Bridge', '마인드브릿지 맨': 'MIND BRIDGE MEN',
    '마인드브릿지 우먼': 'MIND BRIDGE WOMEN', '마일스톤 커피 로스터스': 'MILESTONE COFFEE ROASTERS', '마일즈앤마일즈앤마일즈': 'MILESANDMILESANDMILES',
    '마조네': 'MAJONE', '마지셔우드': 'MARGESHERWOOD', '마켓 X 레 벤자민': 'MARKET X LES BENJAMINS', '마크곤잘레스': 'Mark Gonzales',
    '마티스 더 큐레이터': 'MATISSE THE CURATOR', '마틴골프': 'MARTIN GOLF', '마틴로즈': 'MARTINE ROSE', '마틴플랜': 'MARTINPLAN',
    '마하그리드': 'mahagrid', '말렌': 'MALEN', '매너그램': 'MANNERGRAM', '매니아매스': 'MANIAMASS', '매니악 골프': 'MANIAC GOLF',
    '매드고트': 'MADGOAT', '매드마르스': 'MADMARS', '매든': 'MADDEN', '매버릭': 'MAVERICK', '매치글로브': 'MATCHGLOBE',
    '맥우드건': 'MAC WOODGUN', '맨인정글': 'MAN IN JUNGLE', '머니사이드업': 'MONEY SIDE UP', '머드솔트': 'MUD SALT', '머렐': 'MERRELL',
    '머쉬부쉬': 'MUSHEBUSH', '머슬암드': 'MUSCLE ARMED', '머신': 'MACHINE', '메론스위치': 'MELON SWITCH', '메르시앤에스': 'MERCI&S',
    '메르츠 비 슈바넨': 'MERZ B. SCHWANEN', '메리먼트': 'MERRIMENT', '메리제임스': 'MARYJAMES', '메버릭': 'MAVERICK', '메아': 'MEA', '메이버유': 'MAYBEU',
    '메이크어토스트': 'MAKE A TOAST', '메인부스': 'MAINBOOTH', '메종 마르지엘라': 'Maison Margiela', '메종246': 'MAISON246',
    '메종246_어패럴': 'MAISON246_APPAREL', '메종바인': 'MAISON BINE', '메종미네드': 'MAISON MINED', '메종키츠네': 'Maison Kitsuné',
    '메츠': 'METS', '메타퍼 포 우먼': 'METAPHER FOR WOMEN', '멜란지랩': 'MELANGE LAB', '멧앤멜': 'MET&MEL', '모노소잉': 'MONO SEWING',
    '모노피스파': 'MONO PI SPA', '모노하': 'MONOHA', '모더먼트': 'MODERMENT', '모데스티': 'MODESTY', '모드나인': 'MODNINE',
    '모드리미트': 'MODLIMIT', '모디모디': 'MODI MODI', '모르': 'MOHR', '모블러': 'MOVLER', '모스': 'MOSS', '모스가든 1919': 'MOSS GARDEN 1919',
    '모스포츠': 'MOSPORTS', '모아': 'MOA', '모어아웃': 'MOREOUT', '모이아': 'MOIA', '모이프': 'MOIF', '모트': 'MOTT', '모티패스트': 'MOTIFEST',
    '모헤': 'MOHAE', '몰리올리': 'MOLLIolli', '몽벨': 'montbell', '몽슈슈': 'MONCHOUCHOU', '몽플리쎄': 'MONPLISSE', '몽플리쎄 맨즈': 'MONPLISSE MENZ',
    '무디디': 'MUDIDI', '무라': 'MURA', '무브 나이브': 'MOVE NAIVE', '무신사 스탠다드': 'musinsa standard', '무센트': 'MUSCENT',
    '무아르무스': 'MOIREMUS', '무어니': 'MUERNI', '문달': 'MOONDAL', '문리': 'MOONLEE', '문선': 'MOONSUN', '문수권세컨': 'MSKN2ND',
    '문스워드': 'MOONSWARD', '뮐': 'MHULL', '미나브': 'minav', '미나수': 'MINASU', '미니멀웍스': 'MINIMAL WORKS',
    '미니멀프로젝트': 'MINIMAL PROJECT', '미드나잇 무브': 'MIDNIGHT MOVE', '미드나잇모먼트': 'MIDNIGHT MOMENT', '미드앤로우': 'MIDN LOW',
    '미드에어': 'MIDAIR', '미들로': 'MIDDLOW', '미디어(82)': 'MEDIA(82)', '미미카위': 'MIMICAWE', '미세키서울': 'MISEKI SEOUL',
    '미수아바흐브': 'MISU A BARBE', '미스터리 피플 리서치': 'MYSTERY PEOPLE RESEARCH', '미스페라': 'MISPERA', '미언더': 'MEUNDER',
    '미치코런던 코시노': 'MICHIKO LONDON KOSHINO', '민더리': 'MINDERRY', '밀레': 'Millet', '밀레클래식': 'Millet Classic',
    '밀로 아카이브': 'MILO ARCHIVE', '밀로 우먼': 'MILO WOMEN', '밈 더 워드로브': 'MIM THE WARDROBE',

    # ㅂ
    '바나나시스터즈': 'BANANA SISTERS', '바니쉬먼트': 'VARNISHMENT', '바스락': 'BASRAC', '바스바타': 'VASVATA', '바스통': 'BASTONG',
    '바시카': 'BASICA', '바우프': 'BAUF', '바이닉': 'BYNIC', '바이엘': 'BYEL', '바이크': 'BIKE', '바토너': 'BATONER', '바튼웨어': 'BATTENWEAR',
    '반스': 'Vans', '반원 아틀리에': 'BANWON ATELIER', '반츠': 'Bants', '발란사': 'BALANSA', '발란트': 'VALANTE', '발로렌': 'VALOREN',
    '발루트': 'BALOOT', '배드블러드': 'BADBLOOD', '배드블루': 'BADBLUE', '배러댄서프': 'BETTER THAN SURF', '배럴': 'BARREL',
    '백씨': 'BAEKC', '백야드챔프': 'BACKYARD CHAMP', '밴웍스': 'BANWORKS', '버드와이저': 'Budweiser', '버뮤다 그래스': 'BERMUDA GRASS',
    '버블피스': 'BUBBLE PIECE', '버빌리안': 'BUBILIAN', '버켓': 'BUCKET', '벌': 'BEOL', '벌스데이수트': 'BIRTHDAYSUIT', '벗딥': 'BUTDEEP',
    '벗튼': 'BUTTON', '벙커버스터': 'BUNKER BUSTER', '베네통': 'BENETTON', '베러댄88': 'BETTERTHAN88', '베로니카 이펙트': 'VERONICA EFFECT',
    '베르노': 'VERNO', '베르크로스터스': 'BERK ROASTERS', '베를린포토북디스트리뷰션': 'BERLIN PHOTOBOOK DISTRIBUTION', '베베드피노': 'BEBEDEPINO',
    '베이루트': 'BEIRUT', '베이버스': 'VAVERS', '베이스레인지': 'BASERANGE', '베이스모먼트': 'BASE MOMENT', '베이직 하우스': 'BASIC HOUSE',
    '베이컨트': 'VACANT', '베이프': 'BAPE', '베테제': 'VETEZE', '벤들스': 'BENDLS', '벤시몽': 'Bensimon', '벤트': 'VENT',
    '벨로엘': 'VELOEL', '벨리아르': 'BELIAR', '벨리에': 'BELLIER', '벨리프': 'BELIEF', '벳우먼': 'VETWOMAN', '보기보이즈': 'BOGEY BOYS',
    '보나츠': 'BONATZ', '보나츠 팔레트': 'BONATZ PALETTE', '보스': 'BOSS', '복복': 'BOKBOK', '본로우': 'BONE LOW', '본챔스': 'BORN CHAMPS',
    '본투윈': 'BORN TO WIN', '볼디스트': 'BOLDEST', '볼라이프': 'BALLLIFE', '부기홀리데이': 'BOOGIE HOLIDAY', '부디무드라': 'BUDHI MUDRA',
    '부르르': 'BRRR', '부희': 'BUHEE', '분더캄머': 'WNDERKAMMER', '뷰오리': 'VUORI', '뷰티풀데이즈': 'BEAUTIFUL DAYZ', '브라바도': 'BRAVADO',
    '브라운야드': 'BROWNYARD', '브라이언 베리': 'BRIAN BERRY', '브랜디드': 'BRANDED', '브론슨': 'BRONSON', '브롬톤 런던': 'BROMPTON LONDON',
    '브루먼': 'BRUMAN', '브루클린웍스': 'BROOKLYN WORKS', '브룩스브라더스': 'Brooks Brothers', '브릭': 'BRIC', '브릴먼스': 'BRILLMONTH',
    '브이엔와이스튜디오': 'VNY STUDIO', '브이투': 'V2', '블라블라키아': 'BLABLAH KIA', '블라인드파일즈': 'BLIND-FILES', '블랙블론드': 'BLACKBLOND',
    '블랙야크': 'BLACKYAK', '블랙하인드': 'BLACKHIND', '블랭크룸': 'BLANK ROOM', '블랭크룸 우먼': 'BLANK ROOM WOMEN', '블러': 'BLUR',
    '블레티': 'BLETTI', '블로어': 'BLOWER', '블론드나인': 'BLOND NINE', '블루디 블루': 'BLUEDY BLUE', '블루브릭': 'BLUEBRICK',
    '블루썬플라워': 'BLUE SUNFLOWER', '비건타이거': 'VEGAN TIGER', '비긴202': 'BEGIN202', '비나이스': 'BENICE', '비디알': 'BDR',
    '비르반테': 'VIRVANTE', '비뮈에트': 'BMUET(TE)', '비바셔스': 'VIVACIOUS', '비바스튜디오': 'VIVASTUDIO', '비범스': 'B-BUMS',
    '비비씨 어스': 'BBC EARTH', '비비안웨스트우드': 'Vivienne Westwood', '비슬라': 'VISSLA', '비슬로우': 'BESLOW',
    '비아봉드비아': 'VIA BONG DE VIA', '비에스래빗': 'BSRABBIT', '비엘비티': 'BLBT', '비욘드 클로젯': 'BEYOND CLOSET',
    '비지트인뉴욕': 'VISIT IN NEWYORK', '비트니크': 'BEATNIQ', '비플랫베네통': 'BFLAT BENETTON', '비헤비어': 'BEHEAVYER',
    '빅웨이브컬렉티브': 'BIG WAVE COLLECTIVE', '빅유니온': 'BIG UNION', '빅토리아슈즈': 'VICTORIA SHOES', '빈티지 아카이브 클럽': 'VINTAGE ARCHIVE CLUB',
    '빌라봉': 'BILLABONG', '빔블': 'VIMBLE', '빠니깔레': 'Panicale',

    # ㅅ
    '사스콰치 패브릭스': 'Sasquatchfabrix.', '사운즈굿': 'SOUNDS GOOD', '사운즈라이프': 'SOUNDS LIFE', '사일런트 소사이어티': 'SILENT SOCIETY',
    '사일런트실러블': 'SILENT SYLLABLE', '삭스어필': 'SOCKS APPEAL', '산그로우': 'SANGROW', '산산': 'SAN SAN GEAR', '살로몬': 'Salomon',
    '살롱드서울 포 맨': 'SALON DE SEOUL FOR MEN', '상민': 'SANGMIN', '샌드사운드': 'SAND SOUND', '샌드파이퍼': 'SANDPIPER',
    '샘소이 샘소이': 'Samsoe Samsoe', '생긴스튜디오': 'SAENGGIN STUDIO', '샤카웨어': 'SHAKA WEAR', '샵엠': 'SHOP AM', '서기': 'SEOKI',
    '서라운디드위드': 'SURROUNDED WITH', '서리얼 벗 나이스': 'Surreal But Nice', '서서': 'SEOSEO', '서스테인': 'SUSTAIN', '서유': 'SEOYOO',
    '서지웨어': 'SURGEWEAR', '서티파이드': 'CERTIFIED', '서피스에디션': 'SURFACE EDITION', '선데이후르츠마켓': 'SUNDAY FRUITS MARKET',
    '선플라워': 'SUNFLOWER', '세니트': 'SENITT', '세러데이 뉴욕시티': 'SATURDAYS NYC', '세러데이 레저 클럽': 'SATURDAY LEISURE CLUB',
    '세르지오 타키니': 'SERGIO TACCHINI', '세실 앤 세드릭': 'CECIL AND CEDRIC', '세아랑': 'SAERANG', '세울리앙': 'SEOULIENT',
    '세이지': 'SAIGE', '세이지 네이션': 'SAGE NATION', '세이지먼트': 'SAGEMENT', '세이지힐': 'SAGEHILL', '세인트제임스': 'SAINT JAMES',
    '세인트페인': 'SAINTPAIN', '세일레이싱': 'SAIL RACING', '세컨모놀로그': 'SECOND MONOLOGUE', '세컨스킨': 'SECONSKIN', '세터': 'SATUR',
    '센테스': 'SENTES', '센토르': 'CENTAUR', '센티본즈': 'SENTI BONES', '셋업이엑스이': 'SETUP-EXE', '셔터': 'SHIRTER', '셰프트': 'CHEFT',
    '소루': 'SORU', '소머셋': 'SOMERSET', '소이유': 'SOIYU', '소프터': 'SOFTER', '소프트캐비넷': 'SOFT CABINET', '소프트코너': 'SOFT CORNER',
    '소프트하이픈': 'SOFT HYPHEN', '솔트레인': 'SALT RAIN', '솔티': 'SALTY', '수바코': 'SUBACO', '수비': 'KSUBI', '수수무': 'SUSUMU',
    '수아레': 'SUARE', '수에뇨스튜디오': 'SUENOSTUDIO', '수오마르떼': 'SUOMARTE', '수코이': 'SUKOI', '수프라': 'SUPRA', '숲': 'SOUP',
    '쉘코퍼레이션': 'SHELL CORPORATION', '쉬스튜디오': 'SHESTUDIO', '슈슈통': 'SHUSHU/TONG', '슈퍼서브': 'SUPERSUB',
    '스내피커들': 'SNAPPYCUDDLES', '스낵컬쳐': 'SNACK CULTURE', '스노우피크': 'SNOW PEAK', '스노우피크 어패럴': 'SNOW PEAK APPAREL',
    '스노우피크 어패럴 키즈': 'SNOW PEAK APPAREL KIDS', '스누지': 'SNOOZY', '스미스아머': 'SMITH-ARMOR', '스왈로테일': 'SWALLOWTAIL',
    '스웨이드': 'SWADE', '스웰맙': 'SWELLMOB', '스위브': 'SWIB', '스위치123': 'SWITCH123', '스위트숲': 'SWEET SOUP', '스윔스': 'SWIMS',
    '스카이보틀': 'SKYBOTTLE', '스컬프터': 'SCULPTOR', '스케이터락': 'SK8ER ROCK', '스케쳐스': 'SKECHERS', '스코타': 'SCOTA',
    '스크랩': 'SCRAP', '스키마 도식': 'SCHEMA DOSIK', '스탠다드오브아이비': 'STANDARD OF IVY', '스탠드먼츠': 'STANDMENTS', '스턴트': 'STUNT',
    '스테레오포닉 사운드': 'STEREOPHONIC SOUND', '스테이지 네임': 'STAGE NAME', '스텝온리': 'STEP ONLY', '스토리 엠에프지': 'STORY MFG.',
    '스톡홀름서프보드클럽': 'STOCKHOLM SURFBOARD CLUB', '스튜': 'STU', '스튜디오 싹스탑': 'STUDIO SOCKSTOP', '스튜디오 톰보이': 'STUDIO TOMBOY',
    '스튜디오 톰보이 엑스': 'STUDIO TOMBOY X', '스튜디오앤파르크': 'STUDIO&PARC', '스트리트 스탠다드': 'STREET STANDARD',
    '스티븐 알란': 'STEVEN ALAN', '스틸네스': 'STILLNESS', '스파이더': 'SPYDER', '스페로네': 'SPERONE', '스페이스 에이지': 'SPACE AGE',
    '스펙테이터': 'SPECTATOR', '스펠에디트': 'SPELEDIT', '스포츠 챔버': 'SPORTS CHAMBER', '스포티앤리치': 'Sporty & Rich',
    '스플래시코드': 'SPLASHCODE', '슬로우 레코드 하우스': 'SLOW RECORD HOUSE', '슬로우애시드': 'SLOWACID', '슬로우포크': 'SLOWPOKE',
    '슬로우휴먼': 'SLOW HUMAN', '슬로코스터': 'SLOWCOASTER', '슬로피세컨즈': 'SLOPPY SECONDS', '슬리피존스': 'SLEEPY JONES',
    '슬릭앤이지': 'SLICK AND EASY', '시그니처': 'SIGNATURE', '시그니피컨트': 'SIGNIFICANT', '시눈': 'SINOON', '시도즈': 'SIDOZE',
    '시리즈': 'series;', '시선': 'SISUN', '시슬리': 'SISLEY', '시어링': 'SEARING', '시에라 디자인': 'SIERRA DESIGNS', '시에클': 'SIECLE',
    '시오타': 'CIOTA', '시월107': 'SIWOL107', '시티브리즈': 'CITY BREEZE', '시티브리즈 포 맨': 'CITY BREEZE FOR MEN',
    '시티스트리트': 'CITYSTREET', '시프트지': 'SHIFT G', '신앤리': 'SHIN&LEE', '싸이클린': 'CYCLIN', '써치410': 'Search410',
    '썬러브': 'SUNLUV', '썸띵굿': 'SOMETHING GOOD', '썸웨어버터': 'SOMEWHERE BUTTER', '썸웨어아웃사이드 하이킹컴퍼니': 'SOMEWHERE OUTSIDE HIKING COMPANY',
    '쎄르페': 'SSERPE', '씨드느와': 'SIDENEUF', '씨씨더블유씨': 'CCWC', '씨씨콜렉트': 'CC collect', '씨씨클럽': 'CC CLUB',
    '씨에씨': 'CEC', '씨커슨': 'SEEKERSON', '씨타': 'SITA', '씨피티에스': 'CPTS', '씬': 'SSIN',

    # ㅇ
    '아날로그 베이스': 'ANALOGUE BASE', '아너더기프트': 'ANOTHER GIFT', '아노블리어': 'ANOBLIR', '아노트': 'ANOT',
    '아놀 by 캠브리지 멤버스': 'A.NOLD BY CAMBRIDGE MEMBERS', '아더로브': 'ATHEROBE', '아더월들리': 'OTHERWORDLY', '아데바': 'ADEVA',
    '아디다스': 'adidas', '아뚜': 'ATTOU', '아람': 'ARAM', '아르댓': 'ARTHAT', '아르메오디': 'ARMEO.D', '아르반': 'ARBAN',
    '아르아율': 'ARAYUL', '아르피오': 'ARPIO', '아머럭스': 'Armor-Lux', '아메리칸 니들': 'AMERICAN NEEDLE', '아메스 월드와이드': 'AMES-WORLDWIDE',
    '아모멘토': 'Amomento', '아모우': 'AMOU', '아모프레': 'AMOFRE', '아무': 'AMU', '아미': 'Ami', '아미디': 'AMIDI', '아비쏘': 'ABISSO',
    '아수에토': 'ASUETO', '아스트레이': 'ASTRAY', '아스파라거스_': 'ASPARAGUS_', '아애우': 'AAEWOO', '아에이오우': 'A.E.I.O.U',
    '아우로': 'AURO', '아우브아워': 'AUBEHOUR', '아울나인티원': 'OWL91', '아웃 오브 하빗': 'OUT OF HABIT', '아웃도어프로덕츠': 'OUTDOOR PRODUCTS',
    '아웃스탠딩': 'OUTSTANDING', '아웃오브바운즈': 'OUT OF BOUNDS', '아워': 'AHWER', '아워데이즈': 'OURDAYS', '아워레가시': 'OUR LEGACY',
    '아워셀브스': 'OURSELVES', '아워컬러': 'OURCOLOR', '아유서울': 'AYOU SEOUL', '아이더': 'EIDER', '아이돈워너셀': 'I DONT WANNA SELL',
    '아이디어엔드': 'IDEAEND', '아이띵소': 'ITHINKSO', '아이러니 포르노': 'IRONY PORNO', '아이멀크': 'IMALK', '아이언더스탠드': 'IUNDERSTAND',
    '아임낫어휴먼비잉': "I am not a human being", '아조바이아조': 'AJOBYAJO', '아카우': 'AKAU', '아카이브 볼드': 'ARCHIVE BOLD',
    '아카이브앱크': 'ARCHIVEPKE', '아켑트': 'ACCPT', '아콘 스튜디오': 'ACORN STUDIO', '아쿠드': 'ACUD', '아크 아카이브': 'ARK ARCHIVE',
    '아크네 스튜디오': 'Acne Studios', '아크테릭스': "ARC'TERYX", '아키클래식': 'AKIII CLASSIC', '아타르': 'ATAR', '아템포': 'A TEMPO',
    '아트 이프 액츠': 'ART IF ACTS', '아틀리에 나인': 'ATELIER NINE', '아티스트웨어': 'ARTISTWEAR', '아포페니안': 'APOPHENIAN',
    '아흐레': 'AHRE', '안다르': 'andar', '안데르센 안데르센': 'Andersen-Andersen', '안젤로비안코': 'ANGELO BIANCO',
    '알레산드로 엔리케': 'ALESSANDRO ENRIQUEZ', '알리스': 'ALICE', '알에스브이피': 'RSVP', '알에스에스씨': 'RSSC', '알케미스트': 'ALCHEMIST',
    '알테': 'ALTE', '알테아': 'ALTEA', '알파인더스트리': 'Alpha Industries', '알파카': 'ALPAKA', '암피스트': 'AMFEAST',
    '애니타임로릭': 'ANYTIME RORIC', '애드슬로우': 'ADD SLOW', '애드오프': 'ADDOFF', '애드호크': 'AD HOC', '애쉬아워': 'ASHHOUR',
    '애스플래폼': 'ASPLATFORM', '애습': 'AESP', '애프터눈라이브': 'AFTERNOON LIVE', '애프터프레이': 'AFTER PRAY', '앤니즈': '&NEEDS',
    '앤더슨벨 포 맨': 'ANDERSSON BELL FOR MEN', '앤더슨벨 포 우먼': 'ANDERSSON BELL FOR WOMEN', '앤드원더': 'AND WANDER', '앤드지': 'ANDZ',
    '앤커버': 'NCOVER', '앨빈클로': 'ALVINCLO', '앳모어': 'ATMORE', '앵글런': 'ANGLAN', '어고우': 'ERGOW', '어나더리더': 'ANOTHER LEADER',
    '어나더에이': 'ANOTHER A', '어나더오피스': 'ANOTHER OFFICE', '어낫띵': 'A NOTHING', '어널러코드': 'ANULLERCODE', '어널로이드': 'UNALLOYED',
    '어니스트 크로커': 'ERNEST CROKER', '어랜': 'ERREN', '어레이드': 'ARRAYED', '어반드레스': 'URBAN DRESS', '어반디타입': 'URBANDTYPE',
    '어반사이드 어패럴': 'URBANSIDE APPAREL', '어반스터프': 'URBANSTOFF', '어반에이지': 'URBANAGE', '어반플레이어스': 'URBANPLAYERS',
    '어센트시티': 'ASCENT CITY', '어스': 'US', '어썸스튜디오': 'AWESOME STUDIO', '어웨이크 뉴욕': 'AWAKE NY', '어커버': 'ACOVER',
    '어텐즈': 'ATTENZ', '어퍼스트로피 콤마 (에이콤마)': 'APOSTROPHE COMMA (ACOMMA)', '어프레쉬': 'AFRESH', '언네임드': 'UNNAMED',
    '언노운블루': 'UNKNOWNBLUE', '언더베이스': 'UNDERBASE', '언더아머': 'Under Armour', '언더커버': 'UNDERCOVER', '언더프레셔': 'UNDERPRESSURE',
    '언라이크룩': 'UNLIKELOOK', '언레스': 'UNLESS', '언리미트': 'UNLIMIT', '언바운디드 어위': 'UNBOUNDED AWE', '언아웃핏': 'UN OUTFIT',
    '언어펙티드': 'UNFFECTED', '언유주얼노말': 'UNUSUAL NORMAL', '언지미크': 'UNZIMIQUE', '언티지': 'UNTAGE', '얼킨': 'ULKIN',
    '얼킨캔버스': 'ULKIN CANVAS', '엄브로': 'UMBRO', '에드워드맥스': 'EDWARDMAX', '에든버러 클럽': 'EDINBURGH CLUB', '에디션': 'EDITION',
    '에뛰드': 'ETUDE', '에러스 익셉티드': 'ERRORS EXCEPTED', '에르디': 'ERDE', '에르에르': 'RR', '에리즈': 'ARIES',
    '에메모가든': 'EMEMO GARDEN', '에스릿 스튜디오': 'ESRIT STUDIO', '에스실': 'S.SILL', '에스에스와이': 'SSY', '에스엘비에스': 'SLBS',
    '에스엠에이 슈즈': 'SMA SHOES', '에스이에스티': 'SEST', '에스티코': 'STCO', '에스파이': 'ESFAI', '에스파이벗': 'ESPIBUT',
    '에스피엔케이': 'SPNK', '에스피오나지': 'ESPIONAGE', '에이글': 'AIGLE', '에이알씨': 'ARC', '에이오와이': 'AOY', '에이이에이이': 'AEAE',
    '에이전트픽': 'AGENTPEEK', '에이징씨씨씨': 'AGINGCCC', '에이치덱스': 'HDEX', '에이치에이트': 'H8', '에이치지비비 스튜디오': 'HGBB STUDIO',
    '에이카화이트': 'AECA WHITE', '에이콕': 'ACOK', '에이톤': 'ATON', '에이트디비젼': '8DIVISION', '에이펙스디자인': 'APEX DESIGN',
    '에인트크랙': 'AINTCRACK', '에임스윙': 'AIMSWING', '에즈카톤': 'AEZKATON', '에터': 'ETTER', '에트르세실': 'ETRE CECILE',
    '에폭': 'EPOCH', '에프디알': 'FDR', '에프엠91.02': 'FM91.02', '에피그램': 'EPIGRAM', '에피타이트': 'EPITITE',
    '엑서사이즈': 'EXERCISE', '엑스컨테이너': 'X-CONTAINER', '엑스톤즈': 'XTONZ', '엑스트라오디너리': 'EXTRAORDINARY', '엔더즌': 'N DOZEN',
    '엔비에이': 'NBA', '엔써이즈예스': 'ANSWERISYES', '엔조블루스': 'ENZO BLUES', '엔쵸비': 'ANCHOVY', '엘런아크': 'ELENARC',
    '엘무드': 'LMOOD', '엘씨브이': 'LCV', '엘씨비엑스': 'LCBX', '엘엠씨': 'LMC', '엘엠알': 'LMR', '엠니': 'EMNI', '엠앤엘': 'M&L',
    '엠엘비': 'MLB', '엠엠아이씨': 'MMIC', '엠엠엘지': 'Mmlg', '엠오': 'MO', '엠오오': 'MOO', '엠티엘': 'MTL', '엠프로파': 'MPROPA',
    '엠피티유': 'MPTU', '영오': 'YOUNGOH', '예스아이씨': 'YESEYESEE', '예일': 'YALE', '오가프': 'OGAF', '오니츠카 타이거': 'Onitsuka Tiger',
    '오닐': "O'NEILL", '오드닷': 'ODD DOT', '오드삭스': 'ODD SOCKS', '오드스튜디오': 'ODDSTUDIO', '오디너리원': 'ORDINARY ONE',
    '오디너리피플': 'ORDINARY PEOPLE', '오디너리홀리데이': 'ORDINARY HOLIDAY', '오디너티': 'ORDINUTY', '오디에스': 'ODS',
    '오리엔탈 유나이티드': 'ORIENTAL UNITED', '오베이': 'OBEY', '오브 서울': 'OF SEOUL', '오브오브': 'OF OF', '오브헤덴': 'OFHEDEN',
    '오션퍼시픽': 'OCEAN PACIFIC', '오스윈': 'OSWIN', '오스트리야': 'AUSTRIA', '오아이오아이 컬렉션': 'OIOI COLLECTION', '오앨': 'OAL',
    '오어슬로우': 'ORSLOW', '오에이에스': 'OAS', '오에프씨': 'OFC', '오에프알 파리': 'Ofr. PARIS', '오오엠엘': 'OOML', '오와이': 'OY',
    '오와이케이': 'OYK', '오우르': 'OURE', '오우오': 'OUO', '오울': 'OWL', '오이에프': 'OEF', '오클리': 'Oakley', '오키오 라운지': 'OKIO LOUNGE',
    '오트리': 'AUTRY', '오파츠': 'OPARTS', '오프그리드': 'OFFGRID', '오프너': 'OPENER', '오프넥': 'OFFNECK', '오프닝': 'OPENING',
    '오프닝프로젝트': 'OPENING PROJECT', '오프앤오프': 'OFF AND OFF', '오프화이트': 'Off-White', '오픈엔드': 'OPENEND', '오픈와이와이': 'OPEN YY',
    '오헤시오': 'OHESIO', '오호스': 'OJOS', '온리드 프로젝트': 'ONREAD PROJECT', '온무드': 'ONMOOD', '온스카': 'ONSKA', '올도우': 'OLDOUGH',
    '올드비': 'OLDBE', '올리브 드랩 서비스': 'OLIVE DRAB SERVICE', '올리브데올리브': 'OLIVE DES OLIVE', '올벗원': 'ALL BUT ONE',
    '올젠': 'OLZEN', '올클래식': 'ALL CLASSIC', '옴펨': 'HOMFEM', '와기': 'WAGI', '와드로브': 'WARDROBE', '와르': 'WAR', '와이 이': 'YIE',
    '와이쓰리': 'Y-3', '와이씨에이치': 'YCH', '와이엠씨엘 케이와이': 'YMCL KY', '와이이이엘': 'YEEL', '와이잭': 'YJACK', '와이케이': 'YK',
    '와일드동키': 'WILD DONKEY', '와일드브릭스': 'WILD BRICKS', '와키윌리': 'WACKYWILLY', '왓에버위원트': 'WHATEVER WE WANT', '왕관': 'WANGGWAN',
    '요넥스': 'YONEX', '요키샵': 'YOKISHOP', '우드비': 'WOODBE', '우든리듬': 'WOODEN RHYTHM', '우마뭉': 'UMAMUNG', '우석': 'WOOSUK',
    '우아': 'UAH', '우알롱': 'WOOALONG', '우프 웨어': 'WOOF WEAR', '울': 'WOOL', '움파': 'UMPA', '워스워드': 'WORDSWORD', '워크마트': 'WORKMART',
    '워크워크': 'WORKWORK', '워터맨즈 카페 바이 노아': "WATERMAN'S CAFE BY NOAH", '원더비지터': 'WONDER VISITOR', '원허닛': 'ONEHUNNNIT',
    '월스와일 무브먼트': 'Worthwhile Movement', '월트해머': 'WALTHAMMER', '웨슬리휴스턴': 'WESLEY HOUSTON', '웨이브유니온': 'WAVE UNION',
    '웬즈데이오아시스': 'WEDNESDAY OASIS', '웰메이드컴': 'WELLMADECOMPANY', '웰빙 익스프레스': 'WELLBEING EXPRESS', '웰터 익스페리먼트': 'WELTER EXPERIMENT',
    '위러브티': 'WE LOVE TEE', '위아이윤': 'WIAIYOON', '위앤던': 'WEANDONE', '위어드 띵스 파운드': 'WEIRD THINGS FOUND', '위칙': 'WICHICK',
    '위캔더스': 'WKNDRS', '윌리엄스버그 뉴욕시티': 'WILLIAMSBURG NEWYORKCITY', '윌슨': 'WILSON', '윗': 'WIT', '유니드가먼츠': 'UNEEDGARMENTS',
    '유니버셜오버롤': 'UNIVERSAL OVERALL', '유니벌시티오브월넛': 'UNIVERSITY OF WALNUT', '유니스튜디오': 'YUNNI STUDIO', '유니어패럴': 'UNIE APPAREL',
    '유니온 발란트': 'UNION VALANT', '유니온 블루': 'UNION BLUE', '유니온브라더후드': 'UNION BROTHERHOOD', '유니폼브릿지': 'UNIFORM BRIDGE',
    '유니핏': 'UNIFIT', '유라고': 'URAGO', '유베이지': 'UBEIGE', '유센틱': 'USENTIC', '유스': 'YOUTH', '유스크루': 'YOUTHCREW',
    '유쓰배쓰': 'YOUTHBATH', '유씨버클리': 'UC BERKELEY', '유씨엘에이': 'UCLA', '유아이 제이아이': 'UIJI', '유앤엘씨': 'UNLC',
    '유어데이': 'YOURDAY', '유에프씨 스포츠': 'UFC SPORT', '유주얼 에딧': 'USUAL EDIT', '유지': 'YOOJI', '유체 프레타 포르테': 'YUCHE PRET-A-PORTER',
    '유희': 'YUHEE', '윤세': 'YOONSAE', '으음키임': 'EUMKEEM', '음양': 'EUMYANG', '이고프리덤랩': 'EGO FREEDOM LAB', '이너프원': 'ENOUGHONE',
    '이니미니': 'INIMINI', '이니즈': 'INIZE', '이레귤러': 'IRREGULAR', '이모셔널리 언어베일러블': 'EMOTIONALLY UNAVAILABLE', '이모잔': 'EMOJEAN',
    '이미스': 'EMIS', '이본느비 앤 스웰로': 'YVONNEB & SWALLOW', '이브닝브링스': 'EVENING BRINGS', '이브세이지': 'EVE SAGE', '이비엠': 'EBM',
    '이상': 'YISANG', '이스트 하버 서플러스': 'EAST HARBOUR SURPLUS', '이스트로그': 'EASTLOGUE', '이스트로그 퍼머넌트': 'EASTLOGUE PERMANENT',
    '이스트서비스샵': 'EAST SERVICE SHOP', '이스트인디고': 'EAST INDIGO', '이스트쿤스트': 'ISTKUNST', '이아': 'IA', '이알': 'ER', '이알에이': 'ERA',
    '이알티알': 'ERTR', '이어스트': 'EARST', '이에스씨스튜디오': 'ESC STUDIO', '이에스엔': 'ESN', '이에이': 'EA', '이예': 'YIE', '이올로': 'IOLO',
    '이우가마카라스': 'IUGAMAKARAS', '이육일이유아이': '2612YUI', '이이': 'YIYI', '이즈': 'IS', '이지오': 'EZIO', '이지오 우먼': 'EZIO WOMEN',
    '이코르': 'ICHOR', '이콤마이': 'ECOMMAI', '이터널유': 'ETERNAL YOU', '이티스': 'EYTYS', '이프엘스': 'IFELSE', '이피디벨롭': 'EPDEVELOP',
    '이피제이티': 'EPJT', '이피티': 'EPT', '익스프레스 홀리데이': 'EXPRESS HOLIDAY', '인더로우': 'IN THE ROW', '인더스트': 'INDUST',
    '인뎁스리포트': 'INDEPTH REPORT', '인사일런스': 'INSILENCE', '인사일런스우먼': 'INSILENCE WOMEN', '인스턴트펑크': 'INSTANTFUNK',
    '인스펙터': 'INSPECTOR', '인지액티브': 'INJIACTIVE', '인차일드': 'INCHILD', '인터섹션': 'INTERSECTION', '인템포무드': 'INTEMPO MOOD',
    '인프랩': 'INFLAB', '인플레이션': 'INFLATION', '일구구공보이': '1990BOY', '일꼬르소': 'IL CORSO', '일로제': 'ILOJE', '일리고': 'ILLIGO',
    '일일이삼육오': '112365', '잇미샤': 'IT MICHAA', '잇자바이브': 'ITZAVIBE', '잇터': 'ITTER', '잉크': 'EENK',

    # ㅈ
    '자주': 'JAJU', '자주 언더웨어': 'JAJU UNDERWEAR', '자크뮈스': 'JACQUEMUS', '재이': 'JAEI', '저스트무드': 'JUST MOOD',
    '제너럴아이디어': 'General Idea', '제로': 'XERO', '제로그램': 'ZEROGRAM', '제멋': 'JEMUT', '제이더블유오 스튜디오': 'JWO STUDIO',
    '제이드골드나인': 'JADE GOLD NINE', '제이리움 포 우먼': 'J.RIUM FOR WOMEN', '제이미웨스트': 'JAMIE WEST', '제이앤루': 'J&ROO',
    '제이에스엔와이 유': 'JS.NY U', '제이엘브': 'JLV', '제이청': 'J.CHUNG', '제이프레스': 'J.PRESS', '젠틀맨즈 클럽': "GENTLEMAN'S CLUB",
    '젤라또 피케': 'GELATO PIQUE', '져지팩토리': 'JERSEY FACTORY', '조거쉬': 'JOGGERSH', '조슈아 샌더스': 'JOSHUA SANDERS',
    '조스라운지': "JO'S LOUNGE", '조우': 'JOWOO', '조질롱': 'JO GEELONG', '존 스메들리': 'JOHN SMEDLEY', '주네시스포츠클럽': 'JUNECY SPORTS CLUB',
    '주앙 옴므': 'JUANG HOMME', '주에로': 'JUERO', '주크': 'ZOOC', '준바이준케이': 'JUUN BY JUUN.K', '준태킴 아티셔널': 'JUNTAE KIM ARTISANAL',
    '줄리아페페': 'GIULIA PEPE', '쥐엠쥐에스': 'GMGS', '지비에이치어패럴': 'GBH APPAREL', '지씨디에스': 'GCDS', '지아니루포': 'GIANNI RUPO',
    '지알텐케이': 'GR10K', '지앤오': 'G&O', '지오다노': 'GIORDANO', '지지지': 'Z Z Z', '질샌더': 'JIL SANDER',
    '질스튜어트뉴욕 맨': 'JILLSTUART NEWYORK MEN', '짓먼 빈티지': 'GITMAN VINTAGE',

    # ㅊ
    '채드프롬': 'CHAD PROM', '챈스챈스': 'CHANCECHANCE', '챔피온': 'Champion', '챕터엑스': 'CHAPTER X', '척': 'CHUCK', '초시': 'CHOSI',
    '최에': 'CHOIE', '츄바스코': 'CHUBASCO', '치키타': 'CHIQUITA', '칙스': 'CHIKS', '칠스포츠클럽': 'CHILL SPORTS CLUB',

    # ㅋ
    '카고브로스': 'CARGOBROS', '카네라': 'KANERA', '카네이테이': 'KANEI TEI', '카락터': 'CARACTER', '카르보네': 'CARBONE',
    '카멜앤오아시스': 'CAMEL&OASIS', '카멜워크': 'CAMEL WORK', '카모메키친': 'KAMOME KITCHEN', '카바 라이프': 'CABA LIFE',
    '카비시': 'CAVISH', '카사블랑카': 'Casablanca', '카셀': 'CASSEL', '카일로': 'KYLO', '카키스': 'KHAKIS', '카테고리9': 'CATEGORY9',
    '카틱 리서치': 'KATIK RESEARCH', '칼라파타르': 'KALAPATAR', '칼리코': 'CALICO', '칼하트 윕': 'Carhartt WIP', '캐리스노트': 'CARRIES NOTE',
    '캐비넷 느와르': 'CABINET NOIR', '캐스퍼': 'CASPER', '캐주얼 매뉴얼': 'CASUAL MANUAL', '캐피디자인': 'CAPIE DESIGN',
    '캑터스도넛마켓': 'CACTUS DONUT MARKET', '캑터스소잉클럽': 'CACTUS SEWING CLUB', '캘리포니아 프로젝트': 'CALIFORNIA PROJECT',
    '캘빈클라인 진': 'Calvin Klein Jeans', '캠프사이드': 'CAMPSIDE', '커넥트엑스': 'CONNECT.X', '커렌트': 'CURRENT',
    '커먼 스웨덴': 'COMMON SWEDEN', '커버낫': 'COVERNAT', '커버낫키즈': 'COVERNAT KIDS', '커스텀멜로우': 'CUSTOM MELLOW',
    '커스텀어스': 'CUSTOM US', '커스텀어클락': 'CUSTOMOCLOCK', '컨셉트컬리지': 'CONCEPT COLLEGE', '컨텐트먼트': 'CONTENTMENT',
    '컬럼비아': 'Columbia', '컬럼비아 유니버시티': 'COLUMBIA UNIVERSITY', '컴젠': 'comgen', '케이스위스': 'K-SWISS', '케이엔드': 'K.END',
    '케이투': 'K2', '케이튼': 'KAYDEN', '케인 피오니어': 'KEIN PIONEER', '케일': 'CAYL', '케즈': 'Keds', '코닥어패럴': 'KODAK APPAREL',
    '코드': 'CODE', '코드그라피': 'Code:graphy', '코들러': 'CODLER', '코디갤러리 by STCO': 'CODI GALLERY BY STCO', '코로츠': 'KOROTS',
    '코스모스': 'COSMOS', '코오롱스포츠': 'KOLON SPORT', '코유': 'COYU', '코이노니아 캔버스': 'KOINONIA CANVAS', '코이세이오 038': 'COISEIO 038',
    '코즈넉': 'COSNUK', '코지모지': 'COZYMOZY', '코케트 스튜디오': 'COQUETTE STUDIO', '코코모코': 'COCOMOCO', '코튼벨': 'COTTONBELL',
    '코페르니': 'COPERNI', '코프위': 'COFWI', '콘센트 12': 'CONCENT 12', '콘티누아': 'CONTINUA', '콜드웜': 'COLDWARM', '콜로신스': 'COLOCYNTH',
    '콜릿': 'COLIT', '콜미베이비': 'CALL ME BABY', '콤팩트 레코드 바': 'KOMPAKT RECORD BAR', '쿠메': 'KUME', '쿠어': 'COOR', '쿠어 우먼': 'COOR WOMEN',
    '쿠키시': 'COOKISH', '쿨트': 'KULT', '쿼리': 'QUERY', '퀵실버': 'QUIKSILVER', '큐스': 'QUES', '큐컴버스': 'CUCUMBERS',
    '큐클리프': 'CUECLYP', '크래커스 커피 로스터스': 'CRACKERS COFFEE ROASTERS', '크럼프': 'CRUMP', '크레이터스': 'CREATORS',
    '크루멤버스온리': 'CREW MEMBERS ONLY', '크리브나인': 'CREVE9', '크리스첼로': 'CRISTALLO', '클래드뮤지엄': 'CLAD MUSEUM',
    '클래식마켓': 'CLASSIC MARKET', '클러스터라운드': 'CLUSTER ROUND', '클럽 액티비티': 'CLUB ACTIVITY', '클레버필드': 'CLEVER FIELD',
    '클로브': 'CLOVE', '클로어': 'CLORE', '클로즈드': 'CLOSED', '키네토': 'KINETO', '키딜': 'KIDILL', '키르시': 'KIRSH',
    '키마우라': 'KIMAURA', '키뮤어': 'KIMUIR', '키미저리': 'KIMMISERY', '키셰리헤': 'KICHERIHE', '키아세': 'KIASE', '키오스크키오스크': 'KIOSKKIOSK',
    '키옥': 'KIOK', '키코지': 'KIKOJI', '키크': 'KEEK', '키트래블': 'KITRAVEL', '키퍼탈리': 'KEEPERTALI', '킥더빗': 'KICK THE BEAT',
    '킨': 'KEEN', '킨치': 'KINCHI', '킬리자로': 'KILIZARO', '킴스 프레시 코튼 마켓': "KIM'S FRESH COTTON MARKET", '킷시': 'KITSH',

    # ㅌ
    '타미진스': 'TOMMY JEANS', '타미힐피거': 'Tommy Hilfiger', '타미힐피거 우먼': 'Tommy Hilfiger Women', '타올쿤': 'TOWELKUN', '타이온': 'TAION',
    '타이핑 미스테이크': 'TYPING MISTAKE', '타일레': 'TAILE', '타임리스스포츠웨어': 'TIMELESS SPORTSWEAR',
    '타카히로미야시타 더 솔로이스트': 'TAKAHIROMIYASHITATheSoloist.', '타코마 후지 레코즈': 'TACOMA FUJI RECORDS', '타티네쇼콜라': 'Tartine et Chocolat',
    '탄즈탄즈탄즈': 'TANTANTANTAN', '탑텐': 'TOPTEN10', '태우': 'TAEWOO', '태이': 'TAEI', '태키': 'TACKY', '탭루덴스': 'TABLUDENS',
    '테네르': 'TENERE', '테니스 보이 클럽': 'TENNIS BOY CLUB', '테이크이지': 'TAKEASY', '테일러스튜디오': 'TAILOR STUDIO', '테켓': 'TEKET',
    '텍스처 제로': 'TEXTURE ZERO', '텍토': 'TEKTO', '텐가': 'TENGA', '텐블레이드': 'TENBLADE', '텐씨': 'Ten C', '토니로렌스': 'TONY LAWRENCE',
    '토니웩': 'TONYWACK', '토마스모어': 'THOMAS MORE', '토바간': 'TOVAGAN', '토브드': 'TOVED', '토에즈': 'TOEZ', '토우토우아카이브': 'TOUTOU ARCHIVE',
    '토잉크': 'TOINK', '토콜': 'TOCOL', '톨로': 'TOLO', '톰브라운': 'THOM BROWNE', '톰스벌스데이': 'TOMS BIRTHDAY', '투어티': '20',
    '투인': 'TWOIN', '투타임즈유': '2XU', '툴룬즈브릭': "TOULOON'S BRICK", '튜드먼트': 'TUDEMENT', '튜뮤': 'TUMU', '트래블': 'TRAVEL',
    '트렁크 프로젝트': 'TRUNK PROJECT', '트레셔': 'THRASHER', '트레통': 'TRETORN', '트로앤토프': 'TROIS N TOP', '트리마치': 'TRIMARCHI',
    '트리밍버드': 'TRIMMINGBIRD', '트리플에이': 'TRIPLE A', '트립르센스': 'TRIPLE SENS', '트립션': 'TRIPTION', '트위드': 'TWEED',
    '틀영': 'TEULYOUNG', '티 리버럴': 'TEE LIBERAL', '티떠블유엔': 'TWN', '티라레프로젝트': 'TIRARE PROJECT', '티메이커': 'T MAKER',
    '티아이포맨': 'T.I FOR MEN', '티알브이알': 'TRVR', '티에파렐': 'TIEPAREL', '티엔알': 'TNR', '티엔지티': 'TNGT', '티크': 'TEEK',
    '틸던': 'TILDEN', '틸버': 'TILVER', '팀버랜드': 'Timberland',

    # ㅍ
    '파나컬트': 'PANACULT', '파르티멘토': 'PARTIMENTO', '파르티멘토 우먼': 'PARTIMENTO WOMEN', '파베르 핑거': 'FABER FINGER', '파브레가': 'FABREGA',
    '파세르': 'PASSER', '파시 아뜰리에': 'FASHI ATELIER', '파우라': 'FAURA', '파운드포켓': 'FOUND POCKET', '파이': 'PIE',
    '파인드칠린': 'FIND CHILLIN', '파쿠아': 'PACOA', '파쿠지': 'PAKUJI', '파타고니아': 'Patagonia', '파히섬': 'PAHI ISLAND',
    '판도라핏': 'PANDORAFIT', '팔렛': 'FALLET', '팔시보': 'FALSIVO', '팔육디': '86D', '팔칠엠엠': '87MM', '팝 트레이딩 컴퍼니': 'POP TRADING COMPANY',
    '패러킷': 'PARAKEET', '팬시클럽': 'FANCY CLUB', '팬암': 'PAN AM', '퍼니피그메이드': 'FUNNY PIG MADE', '퍼렌': 'PERENN',
    '퍼블릭워드로브': 'PUBLIC WARDROBE', '퍼블릭피겨': 'PUBLIC FIGURE', '퍼센테이지 디자인': 'PERCENTAGE DESIGN', '퍼스텝': 'PERSTEP',
    '퍼스트플로어': 'FIRST FLOOR', '펀치드렁크파티즈': 'PUNCH DRUNK PARTIES', '펀치라인': 'PUNCHLINE', '페더다운': 'FEATHER DOWN',
    '페세스': 'FESSES', '페얼스': 'PAIRS', '페이딩마켓': 'FADINGMARKET', '페이리': 'PAIRI', '페이지': 'PAIGE', '페이크 케미컬 클럽': 'FAKE CHEMICAL CLUB',
    '페이크마마': 'FAKEMAMA', '페이퍼보이': 'PAPERBOY', '페퍼시즈닝': 'PEPPER SEASONING', '페프스튜디오': 'PEF STUDIO', '페플': 'PEPL',
    '펜듈럼': 'PENDULUM', '펜필드': 'Penfield', '펠린스튜디오제로': 'FELIN STUDIO ZERO', '펠스파브룩': 'FELS PAR BROOK',
    '펭귄 바이 먼싱웨어': 'PENGUIN BY MUNSINGWEAR', '편마': 'PYUNMA', '포더웨더': 'FOR THE WEATHER', '포르타': 'PORTA',
    '포르투기스 플란넬': 'PORTUGUESE FLANNEL', '포베레': 'POBERE', '포스토': 'POSTO', '포에버21': 'FOREVER 21', '포엑스알': '4XR',
    '포울': 'FOUL', '포즈넘버에잇': 'POSE NUMBER EIGHT', '포지티브 바이브': 'POSITIVE VIBE', '포터리': 'POTTERY', '포트너스': 'FORTNERS',
    '포트오브콜': 'PORT OF CALL', '포프롬파더': 'FOR FROM FATHER', '폴 브레이크': 'PAUL BREAK', '폴뉴아': 'POLNEWAR', '폴라로이드': 'POLAROID',
    '폴러스터프': 'POLEr STUFF', '폴로 랄프 로렌': 'Polo Ralph Lauren', '폴루션': 'POLLUTION', '폴리': 'POLY', '폴카폴카': 'POLKA POLKA',
    '폴트': 'FAULT', '폴햄': 'POLHAM', '폼리쉬': 'FOMLISH', '푸마': 'PUMA', '푸마 바디웨어': 'PUMA BODYWEAR', '퓨처': 'FUTURE',
    '퓨처랩': 'FUTURE LAB', '프라블럼올웨이즈': 'PROBLEM ALWAYS', '프라이': 'FREI', '프라이데이 나이트 골프클럽': 'FRIDAY NIGHT GOLF CLUB',
    '프라이데이미드나잇': 'FRIDAY MIDNIGHT', '프라이하잇': 'FREIHEIT', '프랜틱서비스': 'FRANTIC SERVICE', '프랭클리': 'FRANKLY',
    '프레드페리 어패럴': 'FRED PERRY APPAREL', '프레리 온 아이보리페이퍼': 'PRAIRIE ON IVORY PAPER', '프레부아': 'PREVOIR',
    '프레스톤즈': 'PRESTONZ', '프레임 오프': 'FRAME OFF', '프레클': 'FRECKLE', '프레프': 'PREP', '프렌다': 'FRENDA', '프렌치엘': 'FRENCHIEL',
    '프로그레스': 'PROGRESS', '프로드셔츠': 'PROD SHIRTS', '프로세스': 'PROCESS', '프로스펙스': 'PRO-SPECS', '프로젝트엠': 'PROJECT M',
    '프롬아를': 'FROM ARLES', '프롬에이투비': 'FROM A TO B', '프루이': 'FRUI', '프루타': 'FRUTA', '프리저브드 스테이션': 'PRESERVED STATION',
    '프리즘웍스': 'FRIZMWORKS', '프리키쉬빌딩': 'FREAKISH BUILDING', '프리터': 'FREETER', '프린트베이커리': 'PRINT BAKERY', '프릳츠': 'FRITZ',
    '플라스크': 'FLASK', '플라스틱 보틀 보트 (피비비)': 'PLASTIC BOTTLE BOAT (PBB)', '플라스틱 프로덕트': 'PLASTIC PRODUCT',
    '플라즈마스페어': 'PLASMASHOP', '플라츠클래식': 'PLATZ CLASSIC', '플란 랩스': 'FLAN LABS', '플래니트': 'PLANIT',
    '플랙': 'PLAC', '플랜포아더데이': 'PLAN FOR OTHER DAY', '플레어업': 'FLAREUP', '플레이스 스튜디오': 'PLACE STUDIO', '플레이언': 'PLAYIAN',
    '플렉서블': 'FLEXIBLE', '플로피엔디스크': 'FLOPPY N DISK', '플루크': 'FLUKE', '플리즈프로젝트': 'PLEASE PROJECT', '피도디도': 'FIDODIDO',
    '피브비': 'FBB', '피스메이커': 'PIECE MAKER', '피아네르': 'PIANERE', '피엘라벤': 'FJALLRAVEN', '피오팔': '58',
    '피지컬 디파트먼트': 'PHYSICAL DEPT.', '피크닉': 'PIKNIQ', '피크퍼포먼스': 'PEAK PERFORMANCE', '피피비': 'PPB', '피피피스튜디오': 'PPP STUDIO',
    '핀다웃': 'FIND OUT', '핀블랙': 'PINBLACK', '핀카': 'FINKA', '필더스': 'FIELDERS', '필드매뉴얼': 'FIELD MANUAL',
    '필드워커': 'FIELD WORKER', '필로그램': 'PHILOGRAM', '필로비스놑': 'PHILOBISNOT', '필루미네이트': 'FILLUMINATE', '필슨': 'FILSON',
    '필즈라이크썸머': 'FEELS LIKE SUMMER', '핑크파인애플': 'PINK PINEAPPLE',

    # ㅎ
    '하네': 'HANE', '하드코어해피니스': 'HARDCORE HAPPINESS', '하라고': 'HARAGO', '하우스 오브 써니': 'House of Sunny', '하우스포그': 'HOUSEFOG',
    '하울린': 'HOWLIN', '하울팟': 'HOWLPOT', '하이드로겐': 'HYDROGEN', '하이브로우': 'HIGHBROW', '하이스쿨디스코': 'HIGH SCHOOL DISCO',
    '하이타이드 프랭키': 'HIGHTIDE FRANKIE', '하이투': 'HIGHTWO', '하이하이킹': 'HI HIKING', '하프시코드': 'HARPSICHORD',
    '하프크라이즈 레이아웃': 'HALF KRIZ LAYOUT', '하프페니': 'HALFPENNY', '하하우스': 'HAHOUSE', '한스갤러리': 'HANS GALLERY',
    '할로미늄': 'HALOMINIUM', '해든슈퍼마켓': 'HAEDEN SUPERMARKET', '해브레스': 'HAVELESS', '해브오프듀티': 'HAVE OFF DUTY',
    '해브해드': 'HAVEHAD', '해비즘': 'HAVISM', '해칭룸': 'HATCHINGROOM', '해피요기즈': 'HAPPY YOGIS', '핸드앤몰트': 'HAND AND MALT',
    '핸즈 아이즈 하트': 'HANDS EYES HEART', '허그데이': 'HUGDAY', '허그본': 'HUGBONE', '허자보이에이씨씨': 'HUH JABOY ACC', '허프': 'HUF',
    '헌터': 'HUNTER', '헤레틱': 'HERETIC', '헤이 에디': 'HEY EDDY', '헤이그': 'HEIG', '헤인트': 'HEINT', '헤즈': 'HEZ', '헤티': 'HETTY',
    '헨리코튼': 'HENRY COTTONS', '헬로선라이즈': 'HELLO SUNRISE', '헬븐': 'HELEVEN', '현대컬렉션': 'HYUNDAI COLLECTION',
    '호메로페로': 'HOMERO PERO', '호와스': 'HOWTH', '호웨어': 'HOWEAR', '호이테': 'HOITE', '호즈미': 'HOZMI', '호텔세리토스': 'HOTEL CERRITOS',
    '호텔파리칠': 'HOTEL827', '혼다 모터사이클': 'HONDA MOTORCYCLE', '홀리넘버세븐': 'HOLY NUMBER 7', '홀리데이비지터': 'HOLIDAY VISITOR',
    '홀리선': 'HOLY SUN', '홀리오브': 'HOLY OF', '홀페이퍼': 'WHOLE PAPER', '홈그로운 서플라이': 'HOME GROWN SVPLY', '홈리': 'HOMLY',
    '홉스': 'HOPS', '홍우성': 'HONG WOOSUNG', '화이트 마운티니어링': 'WHITE MOUNTAINEERING', '화합': 'HWAHAP', '효지': 'HYOJI',
    '후러브스아트': 'WHO LOVES ART', '후미토간류': 'FUMITO GANRYU', '후브스': 'HOOBS', '후아유': 'WHO.A.U', '휠라': 'FILA',
    '휴고': 'HUGO', '휴머러스 어카운트': 'HUMOROUS ACCOUNT', '휴먼앤캣': 'HUMAN&CAT', '히든비하인드': 'HIDDEN BEHIND', '히어': 'HERE',
    '히즈핸더': 'HIS HANDER', '히피트리': 'HIPPYTREE', '힌지': 'HINGE', '힐리먼트': 'HEALIMENT',

    '고그린 오브젝트': 'GOGREEN OBJECT', '골든아이': 'GOLDENEYE', '공드린': 'GONDLIN', '구드': 'GUDE', '구아슈': 'GOUACHE',
    '구즈': 'GOOSE', '구호플러스': 'KUHO PLUS', '굿나잇데이브': 'GOODNIGHT DAVE', '그노노이': 'GNNONOY', '그라운드오션': 'GROUND OCEAN',
    '그란데라인': 'GRANDE LINE', '그래니룸': 'GRANNY ROOM', '그레이룸': 'GRAYOOM', '그레이스케일': 'GRAYSCALE', '그레이양': 'GREYYANG',
    '그루': 'GURU', '그리다제이': 'GRIDAJ', '그린버터': 'GREEN BUTTER', '글래헤우그': 'GLAEHEUG', '글램모먼트': 'GLAM MOMENT',
    '기마구아스': 'GIMAGUAS', '길라아카이브': 'GILA ARCHIVE', '김미더영': 'GIMMETHEYOUNG', '까이에': 'CAHIERS', '꼬떼아꼬떼': 'COTE A COTE',
    '꼴라주바캉스': 'COLLAGE VACANCE', '꽁떼르씨엘': 'CONTERCIEL', '꾸드뱅': 'COUP DE VIN', '끌레': 'CLE', '나드빌리지': 'NAD VILLAGE',
    '나루강': 'NAROO KANG', '나인아워즈': 'NINEAWORKS', '나일로라': 'NYLORA', '나츠': 'NACHT', '낫노잉': 'NOTKNOWING',
    '낫띵에브리띵': 'NOTHINGEVERYTHING', '낫유어로즈': 'NOT YOUR ROSE', '낸시부': 'NANCYBOO', '너프': 'NERF', '네벨에브리웨어': 'NEBEL EVERYWHERE',
    '네세서리': 'NECESSARY', '네이로': 'NEIRO', '네이비카운티': 'NAVY COUNTY', '노리그렛': 'NO REGRET', '노미나떼': 'NOMINATE',
    '노앤뮤트': 'NO&MUTE', '노우드': 'NORWOOD', '노이아고': 'NOIAGO', '노코시크': 'NOKOCHIC', '노타': 'NOTA', '노테이블': 'NOTABLE',
    '노티벗나이스': 'NAUGHTY BUT NICE', '노티아': 'NOTIA', '노패키지 프로젝트': 'NO PACKAGE PROJECT', '노피셜노피스': 'NOFFICIALNOFFICE',
    '녹섭': 'NOKSEOP', '논로컬': 'NONLOCAL', '논아덜댄': 'NONE OTHER THAN', '논앤논': 'NONENON', '누브': 'NUV', '누아클레 우먼': 'NOIRCLAIR WOMEN',
    '누우띠': 'NOUITI', '누캐시미어': 'NU CASHMERE', '누핍': 'NUPIP', '뉴얼린': 'NEWALLINN', '느와': 'NOIR', '니브': 'NIV',
    '니어노어': 'NEARNOR', '니주르': 'NIJOURS', '니하운': 'NIHAWN', '닐러': 'NILER', '닐링': 'NEALING', '다이애그널': 'DIAGONAL',
    '닥터블릿': 'DR.VLEET', '담슨 매더': 'DAMSON MADDER', '댄프': 'DANF', '댑': 'DAB', '더 라이브러리 오브': 'THE LIBRARY OF',
    '더 머스켓': 'THE MUSKET', '더 와이앤이': 'THE Y&E', '더 케어링': 'THE CARING', '더 히어': 'THE HERE', '더름': 'THELEUM',
    '더마고': 'DERMAGO', '더미튼': 'THE MITTEN', '더블에스씨 아카이브': 'WSC ARCHIVE', '더블유엠엠': 'WMM', '더블쿼츠': 'DOUBLE QUOTES',
    '더애쉴린': 'THE ASHLYNN', '더엣지': 'THE AtG', '더티스': 'THETEES', '더틴트': 'THE TINT', '더하우스류': 'THE HOUSE RYU',
    '던드롭': 'DAWNDROP', '데누': 'DENOU', '데미지니모닉': 'DAMAGE MNEMONIC', '데바스테': 'DEVASTEE', '데비어퍼': 'DEBB AURA',
    '데비웨어': 'DEVYWEAR', '데이': 'DEI', '델코퍼': 'DELCORPER', '도드': 'DOD', '도로시와': 'DOROSIWA', '도토리숲': 'DOTORI SOOP',
    '도퍼': 'DOPHER', '도프셉': 'DOFFICEPT', '독앤베이': 'DOCK & BAY', '돈워리베이비': "DON'T WORRY BABY", '동령': 'DONG RYUNG',
    '듀이듀이': 'DEW E DEW E', '드 마이어': 'DE MAILLEUR', '드노아': 'DENOI', '드로우핏 우먼': 'DRAW FIT WOMEN', '드멜리': 'DEMERLIE',
    '드미어': 'DEMERE', '드파운드': 'DEPOUND', '드팜므': 'DE FEMME', '드헤베': 'DEHEVE', '디망쉬': 'DIMANCHE', '디센디스': 'DECENDIS',
    '디아서': 'THEARTHUR', '디아트레': 'THEATRE', '디어드': 'DEARD', '디어류': 'DEARRUE', '디어리쉬': 'DEARISH', '디어마이디어': 'DEAR MY DEAR',
    '디어뮤즈': 'DEAR MUSE', '디어케이': 'DEAR K', '딜라이디': 'DELID', '딜라잇풀': 'DELIGHTPOOL', '떨스티클럽': 'THIRSTY CLUB',
    '또이': 'TTOI', '라드레드': 'LAD RED', '라라미미': 'LALAMIMI', '라렌': 'LAREN', '라르고': 'LARGO', '라마로': 'LAMAR',
    '라미네즈': 'LAMINEZ', '라비두': 'LAVIDOU', '라비올렛트': 'LA VIOLETTE', '라세레모니': 'LA CEREMONIE', '라이프롬': 'LYFROM',
    '라인스튜디오원': 'LINE STUDIO ONE', '라츠유': 'LOTS YOU', '라파엘': 'RAPHAEL', '람': 'LAM', '랑거': 'LANGER', '랭5': 'LANG5',
    '랭귀지': 'LANGUID', '러브듀이': 'LOVE DEWY', '러브미몬스터': 'LOVEME MONSTER', '러브참': 'LOVE CHARM', '러프넥': 'ROUGHNECK',
    '런블랙': 'RUNBLACK', '레 바캉스': 'LES VACANCES', '레디투킥': 'READY2KICK', '레먼트웍스': 'LEMENT WORKS', '레베드보야지': 'REVE DE VOYAGE',
    '레브드멍': 'REVE DE MEME', '레브레브': 'REVE REVE', '레스아뜰리에': 'LES ATELIERS', '레아비엔': 'REA BIEN', '레이나모라': 'REINA MORA',
    '레이스': 'LAYCE', '레이어무드': 'LAYER MOOD', '레이에': 'REIE', '레이에이버리': 'LEIGH AVERY', '레이즈미야': 'RAISE MIYA',
    '레이크스튜디오': 'LAKE STUDIO', '레이허': 'RAYHUR', '레주': 'LEJOU', '레터리': 'LETTERIE', '레터프롬문': 'LETTER FROM MOON',
    '레트흐 드 레뚜왈': 'LETTRE DE LETOILE', '레티켓스튜디오': 'LETIQUETTE STUDIO', '렉시스': 'LEXISS', '렌세': 'LENSE',
    '렘플레이스먼트': 'REMPLACEMENT', '렙셋': 'REPSET', '로': 'ROH', '로긴 앤 로지': 'LOGIN & ROSY', '로뉴': 'RONIEU', '로니엘': 'RONIEL',
    '로데프': 'RODEFF', '로레일즈': 'LAURA EILISH', '로르인': 'LAUREIN', '로맨틱타이거': 'ROMANTIC TIGER', '로브로브': 'LOVLOV',
    '로비크': 'ROBIC', '로스': 'LOSS', '로아누크': 'LOANOKE', '로아주': 'ROAJU', '로액슈얼': 'ROAXUAL', '로앤로우': 'RO&LOW',
    '로에': 'LOE', '로우타이드': 'LOWTIDE', '로우틸': 'LOWTILL', '로웨': 'ROWE', '로이로이': 'ROIROI', '로제트': 'ROSETTE',
    '로테이트': 'ROTATE', '로트르드민': 'LAUTRE DE MIN', '루그너': 'LUGNER', '루나키후': 'LUNAKIFU', '루드': 'LLUD', '루미노어': 'LE MINOR',
    '루스': 'RUTH', '루시르주': 'LUCIRUZ', '루즈슬립오버': 'LOOSE SLEEPOVER', '루즈앤라운지': 'ROUGE & LOUNGE', '루텐': 'LUTEN',
    '루틴바이브': 'ROUTINE VIBE', '루프루프': 'LOOPLOOP', '룸페커': 'ROOMPACKER', '르': 'LE', '르 스튜디오': 'LE STUDIO',
    '르가넷': 'LE GARNET', '르나브': 'LENAV', '르네즈미아': 'RENESIMIA', '르누이': 'LENOUI', '르니나': 'LENINA', '르로망': 'LE ROMAN',
    '르로브': 'LEREBE', '르메띠에': 'LE METIER', '르메메': 'LEMEME', '르베를렌': 'LE VERLEN', '르베인': 'LEVEIGN', '르보엔느': 'LEVOENNE',
    '르브아시스': 'LEVOISIS', '르세지엠': 'LE 16EME', '르셀로나': 'LECELONA', '르슈아': 'LECHOIX', '르윗': 'LEWIT', '르이엘': 'LE YIEL',
    '리더블유': 'RE W', '리드': 'LEAD', '리로에': 'LEROE', '리리수': 'LILISU', '리마지': 'LIMAGE', '리메인': 'REMAIN',
    '리메크': 'REMAKE', '리무브': 'REMOVE', '리베스': 'LIBES', '리수스': 'LISUS', '리아시티': 'RIACITY', '리얼리티 픽션': 'REALITY FICTION',
    '리얼미 어나더미': 'REAL ME ANOTHER ME', '리에주': 'LIEGE', '리엘': 'LIEL', '리임': 'RIIM', '리즘': 'RISM', '리코타입': 'RICOTYPE',
    '리틀그로브': 'LITTLE GROVE', '리파인드902': 'REFINED902', '리포스': 'REPOSE', '리플레인': 'REPLAIN', '림드': 'LIMD',
    '링서울': 'LING SEOUL', '마가린 핑거스': 'MARGARIN FINGERS', '마그넷': 'MAGNET', '마끄': 'MAQUE', '마나비스세븐': 'MANAVIS7',
    '마네스': 'MANES', '마누엘 에 기욤': 'MANUEL ET GUILLAUME', '마드마드': 'MADEMADE', '마딘': 'MARDIN', '마레디마리': 'MARE DI MARI',
    '마론에디션': 'MARRON EDITION', '마르디메크르디 악티프': 'MARDI MERCREDI ACTIF', '마리느': 'MARINE', '마메르': 'MAMERE',
    '마스컬렉트': 'MARS COLLECT', '마우솔레움': 'MAUSOLEUM', '마이스': 'MAIS', '마일피': 'MILEAF', '마조팩토리': 'MAJO FACTORY',
    '막스마라': 'MAX MARA', '망고매니플리즈': 'MANGO MANI PLEASE', '매그제이': 'MAGJAY', '매기': 'MAGGIE', '매넌': 'MANNON',
    '맥파이앤타이거': 'MAGPIE AND TIGER', '머즈': 'MUZ', '멀리온': 'MERLION', '멍뭉': 'MUNG MUNG', '메렌스': 'MERENCE',
    '메무아': 'MEMOI', '메종 드 이네스': 'MAISON DE INES', '메종 스페셜': 'MAISON SPECIAL', '메종 클레오': 'MAISON CLEO',
    '메종마레': 'MAISON MARAIS', '메종크렘': 'MAISON CREME', '메큘러': 'MECULAR', '멜라니조이': 'MELANIE ZOY', '멜리앤로즈': 'MELLIE&ROSE',
    '모노크롬': 'MONOCHROME', '모노포비아': 'MONOPHOBIA', '모던에이블': 'MODERNABLE', '모머위켄드': 'MOMURWEEKEND', '모멧': 'MOMET',
    '모센틱': 'MOSENTIC', '모슈파모슈': 'MOSHPAMOSHE', '모스모르': 'MOSMOR', '모어댄라이크': 'MORE THAN LIKE',
    '모어댄파라다이스': 'MORE THAN PARADISE', '모어라이크잇': 'MORE LIKE IT', '모어올레스': 'MORE OR LESS', '모어쥬드': 'MORE JUDE',
    '모우트': 'MOTE', '모의': 'MOEUI', '모이 모이': 'MOI MOI', '모이페어': 'MOIFAIR', '모일리': 'MOILY', '모채': 'MOCHAE',
    '몰리스모먼트': 'MOLLYS MOMENT', '몸': 'MOM', '몽돌': 'MONGDOL', '무드베러': 'MOODBETTER', '무드에디션': 'MOOD EDITION',
    '무무탱': 'MUMUTANG', '무브웜': 'MOVEWARM', '무아르보': 'MUARVO', '무음': 'MUEUM', '무카': 'MUKA', '무트오피스': 'MUTE OFFICE',
    '문탠': 'MOONTAN', '문트': 'MUNT', '뮤에': 'MUE', '뮤제': 'MUSEE', '뮤제드': 'MUSED', '뮤젤': 'MUSEL', '뮤즈무드': 'MUSE MOOD',
    '뮤지엄 오브 피스 앤 콰이엇': 'MUSEUM OF PEACE & QUIET', '뮤지엄오브모던키친': 'MUSEUM OF MODERN KITCHEN', '뮤트렛': 'MUTELET',
    '미네랄': 'MINERAL', '미메메': 'MIMEME', '미미몽드': 'MIMIMONDE', '미스터바이랭': 'MR.BYLANG', '미스테리 디렉션': 'MYSTERY DIRECTION',
    '미스테리어스호텔': 'MYSTERIOUS HOTEL', '미스화이트': 'MISS WHITE', '미쏘': 'MIXXO', '미야우바이미나': 'MYAWOO BY MINA',
    '미케네': 'MYCENAE', '미테': 'MITTE', '민므': 'MINME', '민아송': 'MINA SONG', '바니스 뉴욕': 'BARNEYS NEW YORK',
    '바닐라니트': 'VANILLA KNIT', '바디블루': 'BODY BLUE', '바스켄': 'BASQUEN', '바이바이섭': 'BY BY SUB', '바이서우': 'BY SEOU',
    '바이스어치브유쓰': 'VICE ARCHIVE YOUTH', '바이아틀리에': 'BYATELIER', '바이어스웨어': 'BIASWEAR', '바이탈싸인': 'VITAL SIGN',
    '바일리에': 'VAILLIER', '바트카': 'BATCA', '바하윤': 'BAHAYOON', '발코니인스위트': 'BALCONY IN SUITE', '밤부베베': 'BAMBOOBEBE',
    '방떼': 'VENTEZ', '배배': 'BAEBAE', '배주안': 'BAEJUAN', '백로': 'BAEKRO', '버다나': 'VERDANA', '버뮬라': 'VERMULAR',
    '버터': 'BUTTER', '베뉴엣': 'VENUET', '베다': 'VEDA', '베로니카 포 런던 어패럴': 'VERONICA FOR LONDON APPAREL', '베르봄': 'VERBOM',
    '베르브': 'VERVE', '베르소': 'VERSO', '베리시': 'VERISH', '베이오드': 'BAYOD', '베이지보울': 'BEIGE BOWL', '벨로디네라': 'BELLODINERA',
    '벨류엣': 'VALUET', '벨르마': 'BELLEMA', '벰버': 'VEMBER', '보늬': 'BONUI', '보르': 'BOR', '보브': 'VOV', '보울룬': 'VOULOON',
    '보프': 'BOFFE', '본이': 'BORN-E', '볼': 'VOLE', '분닥세인츠': 'BUNDOCK SAINTS', '뷰어 에끌렛': 'VIEWER ECLAT',
    '브라이튼': 'BRIGHTON', '브렌다 브렌든 서울': 'BRENDA BRENDEN SEOUL', '브리딩룰': 'BREATHING RULE', '브리피스': 'BRIPIECE',
    '브링마이띵즈': 'BRING MY THINGS', '브이브이브이': 'VVV', '브쥬': 'VJOO', '븐츠': 'BNTS', '블랑코드': 'BLANC CODE',
    '블랭크공삼': 'BLANK03', '블러썸에이치컴퍼니': 'BLOSSOM H COMPANY', '블루제이너클럽': 'BLUE JAYNER CLUB', '블리온느': 'BLIONNE',
    '비갠디': 'BEGANDIE', '비노블라': 'VINOWBLA', '비롯': 'BIROT', '비먼': 'BEMON', '비뮤즈맨션': 'BEMUSE MANSION',
    '비바브라운': 'VIVA BROWN', '비브비브': 'VIVBEVIV', '비수스': 'BISUS', '비스킷샵': 'BISCUITSHOP', '비아플레인': 'VIAPLAIN',
    '비애티튜드': 'B ATTITUDE', '비코멜리': 'BICOMELLI', '비콰이엇': 'BEQUIET', '비키니밴더': 'BIKINIVENDER',
    '비터셀즈': 'BITTERCELLS', '비테셴': 'BITTE SCHON', '비피비': 'BPB', '빈폴레이디스': 'BEANPOLE LADIES', '사이렌도감': 'SIREN DOGAM',
    '살롱드서울 포 우먼': 'SALON DE SEOUL FOR WOMEN', '살롱드욘': 'SALON DE YOHN', '샌드베이지': 'SAND BEIGE', '샌디리앙': 'SANDY LIANG',
    '샐러드볼즈': 'SALAD BOWLS', '샤드라마': 'SHAH DRAMA', '샤무스': 'SHAMUS', '샤이티모시': 'SHY TIMOTHY', '샤인온유': 'SHINE ON YOU',
    '샤키리': 'SHAKIRI', '샬라': 'SHALLA', '서니드': 'SUNNEED', '서브셋': 'SUBSET', '서브얼반라이엇': 'SUB_URBAN RIOT',
    '서프먼트': 'SURFMENT', '세니크': 'CENIQUE', '세릭': 'CERRIC', '세실리에 반센': 'CECILIE BAHNSEN', '세이스라': 'SEISLA',
    '세이어': 'SAYEUR', '세이프선데이': 'SAFE SUNDAY', '세컨드 아르무아': 'SECOND ARMOIRE', '섹 바이 리군': 'SEC BY RIGOON',
    '섹시쿠키': 'SEXYCOOKIE', '셀렙샵 에디션': 'CELEBSHOP EDITION', '셀리테일즈': 'CELLY TALES', '셉템버 29': 'SEPTEMBER 29',
    '셉팀': 'SEPTIM', '션메익스클로스': 'SEAN MAKES CLOTH', '소냐레바이': 'SONIAREBY', '소셜그린클럽': 'SOCIAL GREEN CLUB',
    '소이': 'SOE', '소치이': 'SOCHII', '소프트서울': 'SOFT SEOUL', '소플러': 'SOFLA', '소함소함': 'SOHAMSOHAM',
    '솔트앤초콜릿': 'SALT AND CHOCOLATE', '솔티 플라워': 'SALTY FLOWER', '솔티페블': 'SALTY PEBBLE', '솜속': 'SOMSOM',
    '송지오 우먼': 'SONGZIO WOMEN', '수수무 홈': 'SUSUMU HOME', '수아레 우먼': 'SUARE WOMEN', '수아마르': 'SUAMAR', '수카': 'SUKA',
    '수팩': 'SUPACK', '수푸이': 'SUPUYI', '쉬림프': 'SHRIMPS', '슈네': 'SHUNE', '슈아슈슈': 'CHOUACHOUCHOU', '스너기스트': 'SNUGGEST',
    '스미는': 'SIMINEUN', '스와이': 'SWAY', '스윗스윗니스': 'SWEET SWEETNESS', '스캐치드': 'SKETCHED', '스탠다드 블루': 'STANDARD BLUE',
    '스탠아드 우먼': 'STANDAD WOMEN', '스테이 위드 미': 'STAY WITH ME', '스텝어라운드': 'STEP AROUND', '스토레츠': 'STORETS',
    '스토리요가': 'STORYOGA', '스튜디오 니콜슨': 'STUDIO NICHOLSON', '스튜디오 다리': 'STUDIO DARI', '스튜디오 솔트': 'STUDIO SALT',
    '스튜디오 시컨트': 'STUDIO SECANT', '스튜디오 심플멍': 'STUDIO SIMPLEMUNG', '스튜디오 지': 'STUDIO G', '스파클링피스': 'SPARKLING PIECE',
    '스프링크로커스': 'SPRING CROCUS', '슬로 아크': 'SLOW ARK', '슬로우가먼츠': 'SLOW GARMENTS', '슬로우롤리': 'SLOWLOLY',
    '슬로우스탠다드': 'SLOW STANDARD', '슬로피파이': 'SLOPPY PIE', '슬리피곰': 'SLEEPYGOM', '슬림9': 'SLIM9', '시그레이트': 'SEAGREAT',
    '시너진': 'SYNERGIN', '시드시': 'SIDSHI', '시메트릭 퍼센트': 'SYMMETRIC PERCENT', '시야쥬': 'SILLAGE', '시엔느': 'SIENNE',
    '시오': 'SIO', '시오르': 'SIOR', '시티팝즈': 'CITYPOPZ', '신스덴': 'SINCE THEN', '실른': 'SILNE', '싹': 'SSAC',
    '쌀뤼드미엘': 'SALUT DE MIEL', '써스데이 아일랜드': 'THURSDAY ISLAND', '써틴먼스': '13MONTH', '써피': 'SURFEA',
    '썬번프로젝트': 'SUNBURN PROJECT', '쎄무아듀': 'CEST MOI DIEU', '쎄미': 'SEMI', '쏘리, 투 머치 러브': 'SORRY, TOO MUCH LOVE',
    '쏘이르': 'SOIR', '쏘킨': 'SOKIN', '쏭스튜디오': 'SSONG STUDIO', '쓰리투에이티': '328', '씨 뉴욕': 'SEA NEW YORK',
    '씨사샤': 'SISASA', '씨솔트씨': 'SEASALTSEA', '씨씨': 'SICI', '씨엠컬렉션': 'CM COLLECTION', '아가모스': 'AGAMOS',
    '아노에틱': 'ANOETIC', '아누': 'ANU', '아누브아': 'ANOUVOIR', '아더즈': 'OTHERS', '아딧': 'ADIT', '아떼 바네사브루노': 'ATHE VANESSABRUNO',
    '아레나': 'ARENA', '아르카익': 'ARCHAIQUE', '아르토': 'ARTO', '아리': 'ARI', '아리악': 'ARIAK', '아리크.': 'ARIC.',
    '아마듀': 'AMADIEU', '아마베': 'AMABE', '아메리칸빈티지': 'AMERICAN VINTAGE', '아무르': 'AMOUR', '아밀': 'AMILL',
    '아바몰리': 'AVAMOLLI', '아밤 홈': 'AVAM HOME', '아방': 'AVANT', '아비토안젤리코': 'ABITO ANGELICO', '아센테': 'ASCENTE',
    '아수라': 'ASURA', '아스파라고': 'ASPARAGO', '아쎄르': 'ACER', '아에르': 'AER', '아옵트': 'AOPT', '아우어솔티': 'OURSORTIE',
    '아웃셀': 'OUTSELL', '아워코모스': 'OURCOMOS', '아워호프': 'OURHOPE', '아위': 'AHWE', '아유': 'AYOU', '아이넨': 'AINEN',
    '아이디얼리스트': 'IDEALIST', '아이브이에이치엘': 'IVHL', '아이스가든 에이.508': 'ICEGARDEN A.508', '아이아이': 'EYEYE',
    '아이에이치알': 'IHR', '아이엠클레어': 'I AM CLAIRE', '아이토브 서울': 'AITOVE SEOUL', '아이홀릭': 'EYEHOLIC', '아쵸': 'ACHO',
    '아치오': 'ACCIO', '아코크': 'AKOK', '아크라이브': 'ARKLIVE', '아크로': 'ACRO', '아키타이프': 'ARCHITYPE', '아트레': 'ATRE',
    '아티드': 'ATTIDE', '아페쎄': 'A.P.C.', '아포엘': 'APOEL', '알람': 'ALARM', '알크미': 'ALKEMEY', '알키알카': 'ALKI ALKA',
    '알테그리히': 'ALTEGRICH', '앙개': 'ANGAE', '애즈유아': 'AS YOU ARE', '애즈이프': 'AS IF', '애프터글로울': 'AFTERGLOWL',
    '애프터아워즈': 'AFTER HOURS', '애프터홈파티': 'AFTERHOMPARTY', '앤드로스': 'ANDROS', '앤드브러쉬': 'ANDBRUSH',
    '앤아더스토리즈': '& OTHER STORIES', '앤유': 'AND YOU', '앤테': 'ANTE', '얀13': 'YAN13', '얀시시': 'YANSISI',
    '어글리쉐도우': 'UGLY SHADOW', '어나더오피스 우먼': 'ANOTHER OFFICE WOMEN', '어나우트': 'ANOUT', '어다울': 'ADAUL',
    '어라운드율': 'AROUND YUL', '어몽': 'AMONG', '어바드': 'ABAD', '어빗모어': 'A BIT MORE', '어센티': 'ASCENTI', '어오트': 'AOTT',
    '어윗': 'AWIT', '어텐션로우 포 우먼': 'ATTENTIONROW FOR WOMEN', '언더띵': 'UNDERTHING', '언더스탠딩 에디션': 'UNDERSTANDING EDITION',
    '언유즈얼': 'UNUSUAL', '언쿡드': 'UNCOOKED', '얼씽': 'EARTHING', '에고이스트 헤리티지': 'EGOIST HERITAGE', '에나반트': 'ENAVANT',
    '에디터블 시나리오': 'EDITABLE SCENARIO', '에딘느': 'EDINE', '에브모우': 'EVMOW', '에스라티': 'ESLatti', '에스와이리': 'SYLEE',
    '에스와이투씨': 'SY2C', '에스이오': 'SEO', '에어 오브 준': 'AIR OF JUNE', '에어라운지': 'AIRLOUNGE', '에이레브': 'AILEVE',
    '에이리프': 'ALEAF', '에이에이유': 'AAU', '에이와이오스튜디오': 'AYO STUDIO', '에이치에스': 'HS', '에이컨': 'ACON',
    '에잇데이즈어위크': '8DAYS A WEEK', '에잇아워즈': '8HOURS', '에즈메': 'EZME', '에즈이프캘리': 'AS IF CALIE', '에취': 'ETCH',
    '에콘': 'EKON', '에트몽': 'ETMONT', '에프더블유더블유엘': 'FWWL', '에프에이디': 'FAD', '에프에프 컬렉티브': 'FF COLLECTIVE',
    '에프코코로미즈': 'F.COCOROMIZ', '에프터누드': 'AFTERNOOD', '에피스틀': 'EPISTLE', '에핑글러': 'EPINGLER', '엔더포브': 'ND/P',
    '엔오디': 'NOD', '엔오르': 'EN OR', '엘레아노': 'ELEANO', '엘로주': 'ELAUGE', '엘리오티': 'ELLIOTI', '엘씨디씨 티엠': 'LCDC TM',
    '엘에프엠': 'LFM', '엘엘엘디자인스튜디오': 'LLL DESIGN STUDIO', '엘오61': 'LO61', '엘프엘프엘프 아카이브스': 'FFF ARCHIVES',
    '엠디지티': 'MDGT', '엠마 멀홀랜드 온 홀리데이': 'EMMA MULHOLLAND ON HOLIDAY', '엠씨엘': 'MCL', '엠엠더블유': 'MMW',
    '엠엠엠': 'MMM', '엠엠오엠': 'MMOM', '엠오엘': 'MOL', '엣드맹': 'AT DMAIN', '엣프터': 'ETPTER', '엽페': 'YUPPE',
    '영마일웨어': 'YOUNG MILE WEAR', '예디 아카이브': 'YEDI ARCHIVE', '오끌레르': 'OH CLAIR', '오더먼트 바이 보카바카': 'ODERMENT BY VOCAVACA',
    '오데스': 'ODES', '오들리워크샵': 'ODLY WORKSHOP', '오디넌트': 'ORDINENT', '오디에르': 'ODIER', '오떼뜨': 'OATET',
    '오로지': 'OROGI', '오뮤': 'OMU', '오버듀플레어': 'OVERDUEFLAIR', '오베르': 'OVERR', '오브베이지': 'OFBEIGE',
    '오브에르': 'OFHERE', '오브유이': 'OFYUI', '오브이디씨': 'OVDC', '오브이티유': 'OVITU', '오브젝트뮤지엄': 'OBJECT MUSEUM',
    '오브콜스와이낫': 'OF COURSE WHY NOT', '오수': 'OHSU', '오스트카카': 'OSTKAKA', '오아르': 'OAR', '오야니': 'ORYANY',
    '오어': 'OAR', '오어드': 'OARED', '오에프엔': 'OFN', '오엔이': 'ONE', '오운서': 'OWNSER', '오유엘': 'OYUEL',
    '오이소엘 어패럴': 'OISOEL APPAREL', '오조델피': 'OJO DE PEZ', '오즈이즈': 'OZEASE', '오찌': 'OTZ', '오쿠카': 'OKUKA',
    '오토링거': 'OTTOLINGER', '오프닝선샤인': 'OPENING SUNSHINE', '오프레': 'OFRE', '오프온스튜디오': 'OFFON STUDIO',
    '오픈도어스튜디오': 'OPEN DOOR STUDIO', '오플린': 'OPLIN', '오피쉬': 'OFISH', '옥토버세컨드': 'OCTOBER 2ND', '온': 'ONN',
    '온느': 'ONNE', '온더쉘': 'ON THE SHELL', '온센느': 'ONCENE', '온앤온': 'ON&ON', '옴므 걸스': 'HOMMEGIRLS', '와이와이아이엠': 'YYIM',
    '와이즈': 'YSE', '요일': 'YOIL', '요한스킴': 'JOHAN SKIM', '우디콜트': 'WOODYCOLT', '운트에이': 'OUNT A', '웁스마이보이': 'OOPSMYBOY',
    '워브먼트': 'WOVEMENT', '원리추얼': 'ONE RITUAL', '원스스탠다드': 'ONCE STANDARD', '웨어리즈': 'WHERE IS',
    '웬스데이딜라잇': 'WEDNESDAY DELIGHT', '웬위윌': 'WHEN WE WILL', '웰노운': 'WELLKNOWN', '위나님': 'WINANIM',
    '위드아웃썸머': 'WITHOUT SUMMER', '위뜨': 'HUIT', '위러버': 'WERVER', '위먼트': 'WEMENT', '위메농': 'OUIMENON',
    '윈더': 'WINDER', '윈리': 'WINLY', '유노이아': 'EUNOIA', '유니스': 'EUNIS', '유룩': 'YOULOOK', '유르트': 'YURT',
    '유메르': 'YUMER', '유어네임히얼': 'YOUR NAME HERE', '유우프': 'YOOOF', '유제': 'YUZE', '유젠': 'YUZEN', '유즈': 'YUSE',
    '유지떼': 'YUJITE', '유포리치': 'EUPHORICH', '이그닐': 'IGNIL', '이너뮤지엄': 'INNER MUSEUM', '이디티알': 'EDTR',
    '이바네네츠': 'IBANENETZ', '이안 조': 'IAN CHO', '이울라이': 'YIULAI', '이제이노리': 'EJ NORI', '이지지': 'EGG', '이케': 'IKE',
    '이테': 'ITE', '이퓨원트': 'IFYOUWANT', '익스파이어드걸': 'EXPIREDGIRL', '일로일': 'ILOIL', '일루스트리스 일루전': 'ILLUSTRIOUS ILLUSION',
    '일리오': 'ILLIO', '일립시스': 'ELLIPSIS', '잇더즌매터': 'ITDOESNTMATTER', '자라다자라난다': 'JARADAJARANANDA', '잽드': 'ZAPPED',
    '쟈니헤잇재즈': 'JOHNNY HATES JAZZ', '쟈습': 'JATH', '저스트하우스': 'JUSTHOUSE', '제드레페브5': 'JEDREFEB5',
    '제로스트릿': 'ZEROSTREET', '제로플래닛': 'ZERO PLANET', '제이더블유엘': 'JWL', '제이드온더페이퍼': 'JADE ON THE PAPER',
    '제이마크뉴욕': 'JMARC NEWYORK', '제이바이라라': 'J BY LALA', '제이빈야드': 'JVINEYARD', '제이앤그라슨': 'J&GRASON',
    '제인송': 'JAIN SONG', '제인송 보야주': 'JAIN SONG VOYAGE', '조선': 'JOSUN', '조셉앤스테이시 어패럴': 'JOSEPH AND STACEY APPAREL',
    '조이그라이슨': 'JOY GRYSON', '조이앤데이': 'JOY&DAY', '졸리레이드': 'JOLIE LAIDE', '주네시': 'JUNECY', '준준 스페이스': 'JUNJUNE SPACE',
    '쥬시쥬디': 'JUCY JUDY', '쥴리앤칼라': 'JULIE&CALLA', '지수리': 'JISOORI', '지아나': 'GIANNA', '지앤지비': 'GNGB',
    '지에마르': 'GIEMAR', '지제로 송지오 우먼': 'ZZERO SONGZIO WOMEN', '지지비샤': 'GGVX', '지컷': 'G-CUT', '차미즈': 'CHARMIZ',
    '차일디쉬 아카이브': 'CHILDISH ARCHIVE', '참스': 'CHARMS', '채뉴욕': 'CHAEnewyork', '체': 'CHE', '칠이공': '720',
    '카루셀골프': 'CARROUSEL GOLF', '카미노': 'CAMINO', '카바렛': 'CABARET', '카인더베이비': 'KINDABABY', '카키포인트': 'KHAKI POINT',
    '카티지하우스': 'COTTAGE HOUSE', '카프리슈': 'CAPRICIEUX', '캄다운': 'CALM DOWN', '캣캣': 'CATCAT', '커밍 오브 에이지': 'COMING OF AGE',
    '커버낫 우먼': 'COVERNAT WOMEN', '컴포트랩': 'COMFORT LAB', '케리에르': 'CARRIERE', '케이 커런트': 'K.CURRENT',
    '케첩앤머스타드': 'KETCHUP AND MUSTARD', '켈리도나휴': 'KELLY DONAHUE', '켈티': 'KELTY', '코데라': 'CODERA', '코디너리': 'CODINARY',
    '코랄리크': 'CORALIQUE', '코르뷔': 'CORBUS', '코벳블랑': 'COVETBLAN', '코어드': 'CORED', '코엣': 'COET', '코캔클': 'COCANCL',
    '코켓': 'COQUET', '코큐': 'COQU', '코텔로': 'COTELLO', '코티하': 'COTIHA', '코핀': 'COFFIN', '콘치웨어': 'CONCHWEAR',
    '콜리나 스트라다': 'COLLINA STRADA', '콜스킨': 'COLESKIN', '콥키노': 'KOPKINO', '쿄': 'KYO', '쿠로': 'KURO', '쿠오트': 'QUOT',
    '큐리티': 'QURITY', '큐피도': 'CUPIDO', '큘': 'CULE', '크눕': 'KNOOP', '크랭크': 'CRANK', '크로커다일 이너웨어': 'CROCODILE INNERWEAR',
    '크리스틴프로젝트': 'CHRISTINE PROJECT', '크림 스튜디오': 'CREME STUDIO', '크세니아 슈나이더': 'KSENIASCHNAIDER',
    '클라터뮤젠': 'KLATTERMUSEN', '클럿스튜디오': 'CLUT STUDIO', '클렛': 'CLET', '클로르': 'CHLORE', '클로버가든': 'CLOVER GARDEN',
    '클로제스트.': 'CLOSEST.', '클로크': 'CLOKE', '클로트': 'CLOT', '클루니': 'CLUNY', '클린': 'KLEAN', '키메': 'KIME',
    '키지코': 'KIZIKO', '키코베': 'KIKOBE', '킨더살몬': 'KINDER SALMON', '킬루엣': 'KILLUET', '킬리만': 'KILIMAN',
    '킴지수': 'KIMJISU', '킴초애 스튜디오': 'KIMCHOAE STUDIO', '타브': 'TAV', '타임': 'TIME', '타입서비스': 'TYPE SERVICE',
    '타지타': 'TAZITA', '타치 클로딩': 'TACH CLOTHING', '탈리타': 'TALITHA', '탑걸': 'TOPGIRL', '테블': 'TEVEL',
    '테이크에어': 'TAKEAIR', '토새': 'TOSAE', '토이킷': 'TOYKEAT', '톤오브유': 'TONE OF YOU', '투머치택스': 'TOO MUCH TAX',
    '투엘브썸': '12SOME', '트와': 'TWA', '트위': 'TWEE', '티나블로썸': 'TINA BLOSSOM', '티에스에이치': 'TSH',
    '틸다마틸다': 'TILDA MATILDA', '틸아이다이': 'TILL I DIE', '파르아비옹': 'PAR AVION', '파사드패턴': 'FACADE PATTERN',
    '파이브에비뉴': '5AVENUE', '파이시스': 'PISCES', '파이카': 'PAICA', '파인베이': 'FINE BAY', '파인오카인드': 'FINE OF A KIND',
    '파케': 'PAQUET', '파티아라': 'PATIARA', '파퓸드로브': 'PARFUM DE ROBE', '파피요트': 'PAPILLOTE', '팍시': 'PAXI',
    '팩토리얼 레이블': 'FACTORIAL LABEL', '퍼르': 'FURR', '퍼버즈': 'PERVERZE', '퍼블리카 엑스': 'PUBLICA X', '퍼제인': 'PERJAIN',
    '펀프롬펀': 'FUNFROMFUN', '페르트': 'PERTE', '페보서울': 'FEVO SEOUL', '페블엠': 'PEBBLE M', '페스토': 'PESTO', '페이딘': 'FADIN',
    '페이스넌': 'FACENON', '페이우': 'FEIWOO', '페인오어플레져': 'PAIN OR PLEASURE', '페포어': 'PEPOIR', '펠로 아 펠로': 'PELO A PELO',
    '포 유어 아이즈 온리': 'FOR YOUR EYES ONLY', '포그던': 'FOGDUN', '포니테일': 'PONYTAIL', '포레토': 'PORETO', '포머티브': 'FORMATIVE',
    '포셉': 'FORCEP', '포스트썬본': 'POST SUNBON', '포에브': 'FOEBE', '포에토': 'POETO', '포에트서울': 'POET SEOUL',
    '포이어': 'FOYER', '포저': 'POSER', '포제': 'POZE', '포즈간츠': 'POSGZ', '포지트': 'POSIT', '포지프레클즈': 'POSY FRECKLES',
    '포코포스카': 'POCOPOSCA', '포허': 'FORHER', '폴로랄프로렌 이너웨어': 'POLO RALPH LAUREN INNERWEAR', '폴리수엠': 'POLYSOOEM',
    '폴앤앨리스': 'PAUL&ALICE', '퓨레': 'PUREE', '프라크티': 'PRACTI', '프렌즈손데토이': 'FRIENDS SONT DE TOI',
    '프렙포더': 'PREP FOR THE', '프로스앤콘스': 'PROS AND CONS', '프로젝트 웨이브': 'PROJECT WAVE', '프론투라인': 'FRONT2LINE',
    '프롬데이모먼트': 'FROM THE MOMENT', '프롬웨얼': 'FROMWHERE', '프루아 트래블러': 'FFROI TRAVELLER', '프리버07': 'PREVER07',
    '프리베일': 'PREVAIL', '프리시': 'PRECIEUX', '프뮤아무르': 'FMU AMOUR', '플램': 'FLAM', '플랫에이티': 'FLAT80',
    '플러피시트러스': 'FLUFFY CITRUS', '플레따': 'FLETA', '플레이그라운드': 'PLAYGROUND', '플레이부': 'PLAYBOO',
    '플로우먼': 'FLOWOMAN', '플로우원': 'FLOWONE', '플로우진': 'FLOWJEAN', '플로움': 'FLOWOOM', '플루나스튜디오': 'FLUNA STUDIO',
    '피그먼트': 'PIGMENT', '피노 블랑코': 'PINOT BLANCO', '피버': 'FEVER', '피에뮤': 'PIEMU', '피오레': 'FIORE',
    '피으': 'PIEU', '피이이피': 'PEEP', '피치덴': 'PEACHDEN', '핀느': 'FINNE', '핀리': 'FINLEY', '필로우': 'PILLOW',
    '필로컬리': 'PHILOCALY', '필로트': 'PILOTE', '핍펫': 'PIPPET', '하가히': 'HAGAHI', '하베크': 'HAVEC', '하수오': 'HASUO',
    '하우스 오브 폰드': 'HOUSE OF POND', '하우스오브차': 'HOUSE OF CHA', '하이버넷': 'HIBERNATE', '하이산': 'HAISAN',
    '하케쉬': 'HACKESCH', '한 코펜하겐': 'HAN KJOBENHAVN', '할란앤홀든': 'HARLAN + HOLDEN', '해바이해킴': 'HAE BY HAEKIM',
    '해브앤해브': 'HAVE N HAVE', '허그유어스킨': 'HUG YOUR SKIN', '헌치': 'HUNCH', '헤니트': 'HENIT', '헤더먼트': 'HEATHERMENT',
    '헨스': 'HENCE', '헬레네파리스': 'HELENE PARIS', '호라호': 'HORAHO', '호엔': 'HOEN', '호쿠스포쿠스': 'HOKUSPOKUS',
    '호프': 'HOPE', '홀리 러브스 러브': 'HOLLY LOVES LOVE', '홀츠베일러': 'HOLZWEILER', '홈바디띵즈': 'HOMEBODYTHINGS',
    '후포': 'HUPO', '휘': 'HWI', '휘게 언더웨어': 'HYGGE UNDERWEAR', '휠라언더웨어': 'FILA UNDERWEAR', '히로인': 'HEROINE',
    '히비스커스블룸': 'HIBISCUSBLOOM', '히쉬': 'HISH', '히어리': 'HEEREE', '히이크': 'HIIK', '히헤': 'HIHE', '힐다': 'HILDA',
    '힙핑크': 'HIP PINK', '1421 라디오 스튜디오': '1421 RADIO STUDIO', '145오피스': '145 OFFICE','210x297 (이일공 이구칠)': '210x297','27와이': '27Y',
    '가니송': 'GARCONSONG','가브리엘 리': 'GABRIEL LEE','가에아': 'GAEA','갈셰': 'GALCHE','감탄브라': 'GAMTANBRA','강자매': 'KANG SISTERS',
    '건지 울른스': 'GUERNSEY WOOLLENS','걸미클': 'GIRL MEETS CLUB','게타상스': 'GETA SANS',"Retriever Club" : "리트리버클럽",

    '가니': 'GANNI','갓바디': 'GODBODY','고블린 웨어': 'GOBLIN WEAR','그라운드브이': 'GROUND.V','낫어스': 'NOTUS','노클레임': 'NOCLAIM',
    '단스킨': 'DANSKIN','더 로켓': 'THE ROCKET','더베를린': 'THE BERLIN','데일리라이크': 'DAILYLIKE','도씨': 'DOSSI','드롭드롭드롭': 'DROP DROP DROP',
    '드웰리': 'DWELLI','디아도라 언더웨어': 'DIADORA UNDERWEAR','띠어리': 'THEORY','란델': 'LANDELL', '레노마수영복': 'RENOMA SWIM','렉토': 'RECTO',
    '록시': 'ROXY','리던': 'RE/DONE','리액티파이': 'REACTIFY','리핏': 'LEPIT','마더': 'MOTHER','마이너스': 'MINUS','맥포스': 'MAGFORCE',
    '메종 미하라 야스히로': 'MAISON MIHARA YASUHIRO','몰든': 'MOLDN','무어': 'MOIR','미민': 'MIMIN','밀리언코르': 'MILLIONCOR','배써': 'BATHER',
    '벌스원': 'VERSE1','베르데마르': 'VERDEMAR','브리노': 'BRINO','블라쿤': 'BLAKOON','블락': 'BLAK','비아리츠': 'BIARRITZ','빈트릴': 'BEEN TRILL',
    '선스펠': 'SUNSPEL','세븐셀라': '7CELLAR','스컬피그': 'SKULLPIG','스퀘어라인': 'SQUARE LINE',
    '슬로우캄포': 'SLOW CAMPO','시티즌 오브 휴머니티': 'CITIZENS of HUMANITY','싱커루프': 'SINKER LOOP','씨네드': 'CINED',
    '씨엘제로': 'CL0','씨엘코코': 'CLCOCO','씨피 컴퍼니': 'C.P. COMPANY','씬 우먼': 'SSIN WOMEN','아이세드': 'I SAID','언코티드 247': 'UNCOATED 247',
    '에노우': 'ENOU','에이골디': 'AGOLDE','엘리자베스 모먼트': 'ELIZABETH MOMENT','엘에스디': 'LSD','엠에스지엠': 'MSGM','오리에나': 'ORIENA',
    '오비노': 'OBINO','오소이': 'OSOI','올 아메리칸 카키스': 'ALL AMERICAN KHAKIS','올드파크': 'OLD PARK','요니아시': 'YONIASHI',
    '우고': 'UGO','위, 아워': 'WE, HOUR','유어해리': 'YOURHARRY','이스트씨': 'EASTSEA','이카이': 'EKAI','일레븐써티': '1130','잇츠 나우 쿨': "IT'S NOW COOL",
    '착한구두': 'CHAKANSHOES','첨스': 'CHUMS','카하나': 'KAHANA','컨투어송': 'CONTOURSONG','코일리': 'COILY','쿠아비노': 'CUAVINO',
    '터키터키': 'TURKEYTURKEY','튀 에스 몽 트레져': 'TU ES MON TRESOR','퍼블리카': 'PUBLICA','포포몬떼': 'POPOMONTE','프람': 'FRAM',
    '프로엔자슐러': 'PROENZA SCHOULER','피스피스': 'PIECEPIECE','피티 토리노': 'PT TORINO','필리플레이스': 'PHILLY PLACE','해즈소울': 'HAZSOUL',
    '화이트 프로젝트': 'WHITE PROJECT',

    '꾸레쥬': 'Courreges','니나코스타': 'NINA COSTA','라이프앤콜렉트': 'LIFE N COLLECT','라이플 페이퍼': 'RIFLE PAPER CO.','렛커즈머스': 'LETCUZMER',
    '로스모어': 'ROSSMORE', '릴리코리': 'LILYCORI','메리모티브': 'MERRYMOTIVE','민씨오': 'MINCIO','버앤버브': 'BUR N VERB',
    '블랭크': 'BLANK','세셉': 'SECEP','셀프 포트레이트': 'SELF-PORTRAIT','앙레베': 'EN REVE','오블라': 'OBLA',
    '유라이크홈': 'ULIKEHOME','코타': 'KOTA','티더블유더블유엘': 'TWWL','할렌': 'HALLEN',

    '러비네': 'LUVINE','로든베베': 'LODENBEBE','마스준': 'MARSJOON','바이누': 'BYNU','비비드솔리드': 'VIVIDSOLID','세컨드호텔': 'SECOND HOTEL',
    '씨폴리': 'SEAPOLLY','아그넬': 'AGNEL','아엘시즌': 'AELSEASON','아이오엣': 'AIOET','아프': 'APEU','어나더봄': 'ANOTHERBOM',
    '오끼뜨': 'OKIT','오지': 'OGG','올인컴플리트': 'ALLINCOMPLETE','위러브': 'WELOVE','조이더블유': 'JOY W','주느세콰': 'JE NE SAIS QUOI',
    '코니': 'KONNY','쿨 이너프 스튜디오': 'COOL ENOUGH STUDIO','타임얼론': 'TIME ALONE','플라주': 'PLAGE','하울스홈': "HOWL'S HOME",
    '해피스트니스': 'HAPPIESTNESS','허비쉬': 'HERBISH'
}
