name: Docker Build

on:
  push:
    branches: [ KyungJae ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t fastapi-app .

      - name: Test Docker image
        run: |
          echo "Testing Docker image..."
          docker run --rm fastapi-app python -c "import main; print('✅ Docker build successful!')"
          docker run --rm fastapi-app python -c "from routers import router_products, router_chatbot; print('✅ All modules working in container!')"

      - name: Test Docker Compose
        run: |
          echo "Testing Docker Compose..."
          docker-compose config
