name: Docker Build

on:
  push:
    branches: [ KyungJae ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          cd FAST_API
          docker build -t fastapi-app .
      - name: Test Docker image
        run: |
          echo "Testing Docker image..."
          docker run --rm fastapi-app python -c "print('✅ Container runs successfully')"
          echo "✅ Docker test passed!"
          
      - name: Test Docker Compose
        run: |
          echo "Testing Docker Compose..."
          docker compose -f FAST_API/docker-compose.yml config
